### ISSUE TITLE
Too many KAKU condition (AND) cards

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#1014]
**What is your Homey version (Settings → System)?**

0.10.5

**What did you try to achieve?**

Use a condition card with both a AMST-606 contact sensor as well as a APIR-2150 Motion Sensor when I found there is two version of the card. Both seem to be doing the same but with different wording. So I just picked one.....

In screenshot below the first two cards are the variations for the 606 condition card, the latter two for the 2150:
![naamloos](https://cloud.githubusercontent.com/assets/22442908/19512155/cb9f3baa-95ea-11e6-83ec-2994e130abab.png)

**What was the result?**

Confusion in my head! :) (But the flow still executed as expected)
...

**What did you expect as result?**

One condition card for each sensor....

**Any other remarks**

...

**Comment by BasKiers** [comment]
Hi,

Thank you for reporting this issue. As of Homey v0.10.5 sensor flow cards are automatically generated by Homey. Therefore the manual flow cards added in the KaKu app are now unnecessary. Unfortunately I cannot simply remove these flow cards from the app because this would break the flows of people who use this card. As a solution I've added the tag `[Deprecated]` to the manually added cards you describe.

Regards, 
Bas

**Comment by Phunkay** [comment]
Works for me, I've updated my flows accordingly... Thanks!
