### ISSUE TITLE
KaKu APA2-2300R turns on automatically

### ISSUE THREAD

**Issue by pimviergever** [athombv/homey#1034]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

Add and control 2 new APA2-2300R units

*Please include detailed steps how we can reproduce the issue*

Synced the remote that came along with the 2 new APA2-2300R. When Homey is turned off, the units listen to the remote (on = on, off = off).
Then I copied the remote signal, when adding the 2 APA2-2300R to Homey.
Both of them respond to the signals send from Homey. When synced with Homey the also listen to the remote.

But both units get turned on automatically by Homey. The bulb in the test screen stays off but I hear the APA2-2300R bein thurned on. On the the test screen I have to turn the bulb on and off again to turn the APA2-2300R off.

**What was the result?**

Why does Homey turn of the new APA2-2300R on automatically?

**What did you expect as result?**

To add 2 new APA2-2300R and that they are not turned on automatically.

**Any other remarks**

This does not happen to 2 other APA2-2300R which I added before.

**Comment by BasKiers** [comment]
Hi,

This is certainly a very strange issue. I cannot think of a cause for this and think the cause is external (not caused by homey) because when homey sends an on signal the toggle in the device card will be toggled on. 

I would suggest further debugging your problem by pairing the two faulty sockets to the buttons of the working sockets and the working sockets to the buttons of the faulty sockets and check if the problem still persists. If you have more information linking this problem to Homey I will further investigate this problem. 

Regards,
Bas

**Comment by pimviergever** [comment]
Hello Bas,

I've checked if it was caused by an external device, but the APA2-2300R are not being turned on when Homey is turned off.
The problem occurs when Homey is turned on.

Which further info do you need?

**Comment by BasKiers** [comment]
Hi,

I am unable to reproduce this issue since there should be no circumstance where the klikaanklikuit app sends signals without user input (except for flows). I assume you do not have flows set for these sockets that are triggered. If you are able to narrow down the problem I could possibly be able to reproduce it and fix it.

Things that are important to narrow the problem down:
Are there any flows that sens 433 signals and could they be the cause
How frequent does this problem occur - does this happen every hour/day/week
Does this happen to these two sockets or these two buttons - you could try to test this by pairing the malfunctioning sockets to the buttons of the working sockets and vice versa
Does this also happen when Homey is off - you could try to test this by leaving Homey off for at least 2 times the frequency rate.
Does this also happen when the devices are not paired to homey - You could test this by removing the malfunctioning sockets from your Homey for at least 2 times the frequency rate
Does this also happen when the kaku app is disabled - you can disable an app in the settings menu of Homey

Regards,
Bas

**Comment by Dijker** [comment]
Hi @BasKiers, I Think I have seen something like @pimviergever mentions here. 

since some updates whenever I restart homey at least with the updates and I think also after a PTP I hear my ASUN650 klick to put the screen up (which is UP already, so nothing happens.) and hear the ASUN 650 fall back to nc 120 seconds later. 

To test I disabled my SunScreen flows, Added a 2nd test-ASUN650 after clearing memory ... Restarted Homey and nothing happend. 
I Re-enabled a suspicous flow:
![image](https://cloud.githubusercontent.com/assets/12412734/19703549/71792a7c-9b04-11e6-92c2-80a338f0b8ff.png)
This triggers like a bit-flip on switching an non-existing device (AC-300)
(Should have been an Virtual ASU650 but temporary replaced it while there was a bug (#898) see Flow descrition her: https://forum.athom.com/discussion/1897/advanced-automatic-sunscreen-with-complex-waf )
I added a Push MSG card to test. 

After a soft reboot I heard the Screen ASUN650 klick again, and got a Push MSG. 
The Test-ASUN650 doesnt have the false trigger. 

This is also true for another flow, it triggers on closing a door to enable the Thermosmart but triggers every restart of Homey. 
![image](https://cloud.githubusercontent.com/assets/12412734/19703934/10ab5cea-9b06-11e6-9e8e-4c6c04eb2911.png)

Both trigger at the end of Homeys startup after both a soft as a hard restart. 
Absolutely without that the attached trigger  (KAKU Signal) was transmitted at that moment, but Homey triggers a flow if it was!

**Comment by pimviergever** [comment]
What eventually solved the problem, after trying the suggestions mentioned before, is testing every flow 1 by 1.
The problem occurred every 4 or 10 seconds. I've disabled all Kaku related flows and started them 1 by 1.
In this case the signal of an old APA2-2300R was identical to a new APA2-2300R. 1 flow would react to two units. 
I've deleted the old unit and re added it. For me this problem is solved
