### ISSUE TITLE
[Speech] 'Rolluiken' is not known as a device

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#1038]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

Use speech to control my 'rolluiken'

**What was the result?**

Homey doesn't do anything because he doesn't understand 'rolluiken' but only listens to 'rolgordijnen'

**What did you expect as result?**

Motion from my 'rolluiken'

**Any other remarks**

Maybe it's a difference between NL and BE, and so possibly other words will not be recognized either?

**Comment by bvdbos** [comment]
Rolluiken are situated on the outside, rolgordijnen on the inside of the house? Is this the same in Flanders?

**Comment by Fire69** [comment]
Yeah, I guess. :-)

Did forget to mention that it used to work pre 0.10.x
And since they're controlled by Fibaro Roller Shutters, I guess it's supposed to work for 'rolluiken' too :-)

**Comment by Tweake** [comment]
Currently we only have the deviceclass windowcoverings, which includes devices both on the inside and the outside of the window. It make sense to add it since it seems like a fairly common word, so you'll be able to call them "rolluiken" or just "rolluik" after the coming update. Thanks for pointing it out!

**Comment by Fire69** [comment]
It's working as expected now. Thanks for fixing this. :-)
