### ISSUE TITLE
Kaku: Status of Asun 650 gets lost

### ISSUE THREAD

**Issue by Marc1979** [athombv/homey#1042]
**What is your Homey version (Settings → System)?**

0.10.17 (Homey firmware)
2.6.5 (Kaku app version)

**What did you try to achieve?**
Make the status of screen a condition, so if it's opened by the button in the app it not triggers again at a time (flow)

_Please include detailed steps how we can reproduce the issue_
Sometimes the status of the asun is going into "still" (middle button between the up/down arrows). All my asun's are triggerd by time and go open to the half (status change to up/after 12sec status to up, so they will stop). If i watch in the app sometimes the device is going to still so I cannot put the status in a condition. (I have already re-add the device again, still the same problem)

**What was the result?**
Flows are not working 100% with the status from the asun in a condition

**What did you expect as result?**
That the last know status of the asun is correct, so I can put them in a condition of a flow

**Any other remarks**
It worked very well before firmware update 0.10.0 and it is not happening all the time. Also after different Kaku app updates it is not solved

...

**Comment by BasKiers** [comment]
Hi,

While I get what you are trying to do this functionality is intentional. This is because the state of the motor is idle and not up or down. The motor only gets powered for a couple of seconds which means that clicking down once does not always mean the sunscreen is down but could also mean halfway or 1/5th down which I find ambiguous. 

I would suggest creating 2 flows that work like this:
![image](https://cloud.githubusercontent.com/assets/6036127/20412068/d705d9e4-ad24-11e6-9e57-cda9c9e2e531.png)

Now you can use the variable "blinds" to check if your blinds are open or closed and for instance close them when it is about to rain.
![image](https://cloud.githubusercontent.com/assets/6036127/20412117/14925e54-ad25-11e6-92ef-45278b581713.png)

Regards,
Bas

**Comment by Marc1979** [comment]
Yeah, I have made the variables already and it works fine.
But it is still strange that is has worked in a previous firmware version or app version, don't know when it stopped. But this also a sollution. Will close the issue
