### ISSUE TITLE
https://my.athom.com/ offline. Status well Operational 

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#1062]
**What is your Homey version (Settings → System)?**

x.x.x Can't see

**What did you try to achieve?**
Using speech
**Please include detailed steps how we can reproduce the issue**
OK Homey

**What was the result?**
Direct answer: Oeps. Ik kan de server niet bereiken
...

**What did you expect as result?**
Waiting on my question
...

**Any other remarks**
Can't log in. Status stands on Operational
...

**Comment by jeroenvollenbrock** [comment]
Hi!
We are currently not aware of any cloud related issues, and both the speech services and my-athom appear to be operating normally. However, my-athom had scheduled maintenance earlier today. Given that the cloud speech processing and my-athom are two different services that both seem to be unreachable in your case, I'm suspecting your homey does not have a working internet connection. Could you please verify if the issue is:
1. Still currently reproducible
2. Solved after rebooting homey
And let us know your findings afterwards?

**Comment by KroontjesPen** [comment]
Just testing again and speech and logging in are OK now. 
Before making this item I had PTP first and waiting for 20 minutes.

**Comment by jeroenvollenbrock** [comment]
Glad to hear it's working again, please keep in mind that it can take a few minutes after a PTP before Homey has started all apps and made a connection with my-athom. Sorry for the inconvenience!

**Comment by KroontjesPen** [comment]
Even one remark: I couldn't logging in. That is not normal to me.

**Comment by KroontjesPen** [comment]
You may reopen this case because **now** and 2 days earlier it happens again.
