### ISSUE TITLE
Kaku APCR-2300 seen as light and not as socket by homey

### ISSUE THREAD

**Issue by Anamatronic** [athombv/homey#1067]
Homey Firmware Versie: 0.10.9

I want Homey to turn down all lights in a room.

When I ask homey to turn down all lights in my room he does what I ask, but also turns down a KaKu socket (stekkerdoos) APCR-2300 that is not a light ( i use that for my tv and sterio set)

I have pared APCR-2300 as a socket using the the Kaku app and as an AC-1000.

What i would like is that the APCR-2300 is added as socket set and not as a lamp, so when i ask homey to turn down the lights he leaves this on.

...

**Comment by BasKiers** [comment]
Hi, 

The problem is probably due to the "plugged in" device that is chosen during the pairing wizard. If so you should see a little light bulb in the bottom right corner of the device card. You can fix this by removing the device and pairing it again but this time choosing a different "plugged in" device.

Regards,
Bas Kiers

**Comment by Anamatronic** [comment]
Hello Bas,

You are right, problem is now solved!

Many thanks!

Rene
