### ISSUE TITLE
Somfy awning not responding to buttons during pairing

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1085]
**What is your Homey version (Settings → System)?**
1.0.1

**What did you try to achieve?**
Operate a somfy RTS awning (terras knikarmscherm) with Homey during pairing

**What was the result?**
After pressing the pairing button on the remote the screen responds. In the next step the screen responds again, indicating it is paired. However, testing the awning (with or without long signal) does not result in a response. (the animation does work)

**What did you expect as result?**
awning to open during pair test.

**Any other remarks**
Also after the pairing the awning does not respond to button presses., In older versions (before 0.10.x) it did work.

**Comment by BasKiers** [comment]
Hi,

If I am right in the "other remarks" you mean that Homey does not recognize the button presses on your somfy remote. This is intended behavior since Somfy uses a slightly different frequency than the 433mhz frequency Homey is listening to. This means we are able to switch to that frequency when we send a button press but we are not able to simultaneously listen to two frequencies. 

Your main problem is a bit harder to debug. My best guess is that the memory of your somfy motor is full and it cannot store a extra remote (Homey). To fix this you will need to reset the motor. Instructions for this can be found in the manual of the model you have (maybe this pdf will help: https://www.blindschalet.com/pdfs/Installation/programming-rts-motors.pdf). If this does not solve your problem could you please reply on this issue?

Regards,
Bas

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. 

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
