### ISSUE TITLE
feature request: OTA firmware upgrade for ZWAVE devices

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1171]
**What is your Homey version (Settings → System)?**

1.0.4

**What did you try to achieve?**

I have several zwave devices that can get a firmware update Over The Air (OTA). E.g. the fibaro multisensor and the Aeotec multisensor. I only have a Homey as a controller, so I would very much like to be able to do the fw update using Homey! It would probably also solve a lot of device issues that users are experiencing with older device firmwares.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

For Homey to support OTA zwave firmware updates.

**Any other remarks**

See for instance the information at:

https://aeotec.freshdesk.com/support/solutions/articles/6000036562-how-do-i-upgrade-the-firmware-for-multisensor-6-

https://forum.fibaro.com/index.php?/topic/21711-fibaro-device-firmware-list/

**Comment by WeeJeWel** [comment]
Actually an app could do this indepdently of Homey, so this might happen in https://github.com/athombv/node-homey-zwavedriver someday.

**Comment by gruijter** [comment]
Do you mean it is already possible with the present driver? Or that you will extend the driver to be able to do this? :) 👍

**Comment by WeeJeWel** [comment]
The APIs are already there (because it's simply a matter of sending data to a Node using COMMAND_CLASS_FIRMWARE_UPDATE), so in fact everyone could add support for it already.

**Comment by robertraaijmakers** [comment]
Is there a generic place to retrieve the 'data' that needs to be send to the device? Or is this manufacturer specific?

**Comment by WeeJeWel** [comment]
Yeah that's manufacturer specific.

**Comment by Inversion-NL** [comment]
I can see some advantages when using an app because it then can utilize Homey's settings screen to have a user facing interface for when doing firmware updates.

**Comment by WeeJeWel** [comment]
It's probably best to create an extension in https://github.com/athombv/node-homey-zwavedriver

**Comment by gerjan01** [comment]
Can this be done throug the (in my case) Fibaro app?

**Comment by bvdbos** [comment]
Nope, not yet unless someone creates this extension...

**Comment by WeeJeWel** [comment]
I've contacted Fibaro to provide us with the firmware binaries, but for now no response.

**Comment by daneedk** [comment]
Why wait for Fibaro ;)

https://aeotec.freshdesk.com/support/solutions/articles/6000036562-multisensor-6-firmware-update-6-17-2016-new-information-v1-08-11-02-2016-

https://aeotec.freshdesk.com/support/solutions/articles/6000134294-smart-switch-6-firmware-v1-03-v1-00-update

https://aeotec.freshdesk.com/support/solutions/articles/6000134296-recessed-door-sensor-gen5-ota-firmware-update-v1-13

And some more:

https://aeotec.freshdesk.com/support/home

**Comment by elwin23** [comment]
I second this, got no other zwave controller but have a multisensor 6 from aeotec

**Comment by caseda** [comment]
Even though aeotec updates look like other controllers can use that, its still in their own executable and thus only update-able with an z-wave stick that you can put into your computer.

Not sure if aeon labs will give the raw hex data to the outside world (the data needed for other controllers), or just like fibaro is doing and keeping it very "secret" and to themselves so people Need to buy an fibaro controller or go by a store that gives that possibility.

You can "steal" the hex data, as it is shown in a log, but is cleaned very regularly (every 10-15 lines), and since there is send 2000 - 7500 lines of commands, depending on which device and update, (that's a lot of hexadecimal bytes!) its pretty hard to record all that, and not just _forget_ 1 byte, which will brick your device, and that **doesn't** fall under your guarantee anymore.

For Aeotec devices you can just buy your own z-wave stick for 30 euro's or so, and update, if you have windows that is, their application will not work on mac or linux.

**Comment by WeeJeWel** [comment]
I will close this issue as it's not likely to be implemented in the future, due to manufacturers being very non-cooperative.
