### ISSUE TITLE
feature request: Somfy divice ID adres manual input option

### ISSUE THREAD

**Issue by sebohans** [athombv/homey#1182]
Homey version 1.05
Somfy RTS 2.1.6

I want to manualy add the somfy device id adres in Homey.
I allready added 12+ somfy devices to my domoticz and homeseer with a RFXtrx433E transceiver.
Now I want to add these same device ID's to Homey without the need to pair them again to Homey.
But there is no data input field for that or a database with the paired adresses that i can manually edit .

Can you please add a manual option to add an device id adress in binary or hexadicimal vallue?

**Comment by nattlip** [comment]
is that possible in homeseer 3 , i thought not.

**Comment by sebohans** [comment]
Yes this is possible in homeseer 3. You have to convert the decimal numbers to hexadecimal and use that as the Device id , after that it works.

**Comment by nattlip** [comment]
learned something new. it would indeed be a good feature, then you dont have to reset the blinds all the time when the memory is full of remotes.

**Comment by BasKiers** [comment]
Hi, 

I am aware of this lacking functionality but I do not plan on adding this soon since it could lead to a lot of confusion and support issues when I do enable this. 

But to help you with the issue I've made it possible for a user to override the generated signal in a quite technical way to make this feature usable for people who know what they are doing. You will need to override the `address` AND `id` field (which are the same) of the device data object to the address you know. The address is a string containing a binary representation of the address (So you will need to convert from decimal/hex to binary which you can do with the calculator of your operating system). In the screenshot below I show how to edit the address. Notice that I use the first call with `null` to display the current data and then override it in the second call. Note that your chrome console should have the `pair-iframe` selected in the top left. 

This new feature needs an update of the app and thus will not immediately work for all 433 apps. For now I only updated the KaKu and Somfy app with this feature. In the future this should be added to other athom 433 apps when they get updated.

Regards, 
Bas

![image](https://cloud.githubusercontent.com/assets/6036127/21612616/427167da-d1d2-11e6-8199-9a067077de36.png)

**Comment by sebohans** [comment]
It's not working exactly with me.
I've updated SomfyRTS app.
And I am know trying to change the adress and id.
![image](https://cloud.githubusercontent.com/assets/18574539/21641766/3bf3ddbe-d27e-11e6-924f-b33d3b6b9a7d.png)

I am very new to this so please be patient .

**Comment by sebohans** [comment]
Ok i think I made a typo some where.
I am now a little bit further, but my curtains are still not moving.
![image](https://cloud.githubusercontent.com/assets/18574539/21642466/946a2c56-d282-11e6-9d70-ef57efc88ddf.png)

when i push the test buttons nothing happens even the animation isn't working anymore.
Clicking next will make the device but it won't function.

**Comment by sebohans** [comment]
Hoi Bas,


heb op git hub een comment gedaan het lukt me namelijk net niet.

Ik kan de huidige waarde uitlezen met:   Homey.emit('override_device', null, console.log)


Ook de waarde aanpassen lukt nu.

Homey.emit('override_device', {address: '000000000000001000001101', id: '000000000000001000001101'}, console.log)


Daarna kan ik hem niet testen (animatie van sluitend gordijn loopt ook niet meer)

Als ik op verder druk word er wel een device gemaakt echter werkt deze niet.


Groeten Sebo-Hans

________________________________
Van: Bas Kiers <notifications@github.com>
Verzonden: dinsdag 3 januari 2017 16:38
Aan: athombv/homey
CC: sebohans; Author
Onderwerp: Re: [athombv/homey] feature request: Somfy divice ID adres manual input option (#1182)


Hi,

I am aware of this lacking functionality but I do not plan on adding this soon since it could lead to a lot of confusion and support issues when I do enable this.

But to help you with the issue I've made it possible for a user to override the generated signal in a quite technical way to make this feature usable for people who know what they are doing. You will need to override the address AND id field (which are the same) of the device data object to the address you know. The address is a string containing a binary representation of the address (So you will need to convert from decimal/hex to binary which you can do with the calculator of your operating system). In the screenshot below I show how to edit the address. Notice that I use the first call with null to display the current data and then override it in the second call. Note that your chrome console should have the pair-iframe selected in the top left.

This new feature needs an update of the app and thus will not immediately work for all 433 apps. For now I only updated the KaKu and Somfy app with this feature. In the future this should be added to other athom 433 apps when they get updated.

Regards,
Bas

[image]<https://cloud.githubusercontent.com/assets/6036127/21612616/427167da-d1d2-11e6-8199-9a067077de36.png>

[https://cloud.githubusercontent.com/assets/6036127/21612616/427167da-d1d2-11e6-8199-9a067077de36.png]

-

**Comment by BasKiers** [comment]
Hi,

I tested this method and the animations in the testing screen will not work after you edit the id, the buttons however do send the overridden signal and adding the device should send signals with the overridden address. Are you sure that the id you entered is correct?

Regards,
Bas

**Comment by BasKiers** [comment]
Hi, 

I checked some more and what could be the problem is that Somfy uses a rolling code that increments for each subsequent signal. Homey sends signals starting at 0 and incrementing after each command. However there is a possibility that, since your remote is at a different rolling code for instance 623, that Somfy will ignore the signal of Homey since the rolling codes are to different. This is a problem that only applies to Somfy and I cannot quickly fix.

Regards,
Bas

**Comment by BasKiers** [comment]
Hi,

This issue is still open but we decided not to implement this into the Somfy app since this is to advanced does not offer more/better functionality of the app. Additionally this adds another state on how a device could be added which will be harder to provide support on.

Regards,
Bas
