### ISSUE TITLE
HomeEasy pairing

### ISSUE THREAD

**Issue by florisi** [athombv/homey#1186]
**What is your Homey version (Settings → System)?**

1.0.4

**What did you try to achieve?**

Trying to pair a (HomeEasy) HE333EU without remote.

**What was the result?**

Can't pair the device

**Any other remarks**

I want to pair the device, but I have no remote control for the HomeEasy.

**Comment by BasKiers** [comment]
Hi, 

Pairing the HE333EU without a remote is disabled since in my testing the remote needed to be within 10 centimeters from the socket which would not be usable if you need to hold Homey this close to your socket. Therefore I will not change this in the app that is in the appstore. However I uploaded a version that does enable pairing without the remote which I quickly tested here: https://github.com/athombv/eu.elro.homeeasy/tree/enable-signal-generation . You can sideload this app by following the instructions in this video: https://www.youtube.com/watch?v=lRZLvhF2sfk . After you add the device I would recommend installing the appstore version over it by just clicking install from the appstore again.

Regards,
Bas

**Comment by florisi** [comment]
Bas, the link is not available. (in GitHub)

**Comment by BasKiers** [comment]
Ah, my bad. the repository is private... I will try to make a different workaround then, sorry.

**Comment by BasKiers** [comment]
Hi, 

I've added a workaround in the homeeasy app to open the "generate signal" screen in v1.4.2. When you open the pair wizard at the "press a button on your remote" screen you can click on the pairing wizard (this is needed to gain focus, just click on the remote or something) and then type "generate" on your keyboard. This should open the "generate signal" view which you can follow to pair your socket. Note however that the range still needs to be below 30 centimeters to pair the socket. You could do that by programming it close to Homey and then inserting the socket somewhere else, the programmed signal should still be stored on the socket.

Regards,
Bas

**Comment by florisi** [comment]
Thanks, I will try today.

**Comment by florisi** [comment]
Hi Bas,

I've paired three switches with no problem.
So thank you very much.

Regards,
Floris
