### ISSUE TITLE
Support for Generic 433mhz devices

### ISSUE THREAD

**Issue by soler2000** [athombv/homey#127]
Simple support for generic 433mhz devices such as door bells, smoke detectors etc.  i.e learning mode

**Comment by irritanterik** [comment]
Define generic.
How to identify the device-code's and values from different encoded signals? I thing you need an app for every protocol. Maybe using this: https://github.com/pimatic/rfcontroljs

**Comment by mirakels** [comment]
+1

**Comment by WeeJeWel** [comment]
Our philosophy is that every device should be accompanied by an app. This ensures high quality.

Developer tools to capture 433 MHz signals will be added later.

**Comment by bvdbos** [comment]
A lot of people want this, I don't think this issue should be closed but perhaps just give a lower priority...

**Comment by mirakels** [comment]
This is to easy Athom!
Hoemy was announce as a device to control almost everything in your house with (as long as it has supported transmissian channels, like 433MHz).
Now you state it can only work if there is an app for it.
If you look at the app store then our choices are quite limited at the momen. 

What have you been doing in the last 10 months then? As homey should have been availlble in May 2015!
So 10 months overdue and if you look at the issues list and forums it is already dissapointing the software is described as beta, but as other people already mentioned if feels more like alfa.
And now you just closes issues for bugger reasons.

So far I all I can do is ask homey for the time. My KIKU device is not accepted by home, my 433MHz devices are not supported by homey, 

If you are in beta state at least you should have enough tools so people can experiment with devices
in a sort of /monitoring/ mode. So let the signals come in and present them in a way that developers can analyse them in order to build apps...

We expected more.

**Comment by bvdbos** [comment]
@mirakels What's a kiku-device? KAKU (Klik-Aan-Klik-Uit) = COCO (Click-On-Click-Off) works... Perhaps you rebooted? Then perhaps your 433-sensor didn't come up but that's a different bug ( #102 ) . You should try powering off and on again

**Comment by mirakels** [comment]
Sorry, should have been KAKU (YCT-100 remote with YC-100 socket). 
I rebooted and poweroff/on homey several times and tried over and over again using 0.8.12 and 0.8.17 firmware.

**Comment by filoor** [comment]
i also looking for this

**Comment by matjaz** [comment]
:+1: 

Providing dev tools would help community build apps for devices.

**Comment by WeeJeWel** [comment]
Awesome 433/868 MHz tools are on it's way :-) With raw data recording, target frequency support etc. etc.

**Comment by jcastrol07** [comment]
Hi everyone
Each brand will require its own app? Or should there be a list of other compatible brands for current 433 apps?
Does
For example is there any app currently available for Homey that will allow me to use Radio control Jung devices?. They operate under frequency 433,42 MHz , which I believe is the same frequency as  Somfy 
I did not manage to pair it using Somfy app but should I have able to do it?..
Or with any other current 433 related app?
Thanks

**Comment by mehak-bhatia** [comment]
Is there an update on the 433/868 MHz tools/app? @WeeJeWel

**Comment by xeor** [comment]
Bumping this once more...

**Comment by WeeJeWel** [comment]
Yes, the tools are available here: https://developer.athom.com/tools/signals

We have no plans for 'learning' and 'repeating' 433 Mhz signals.

**Comment by wessta** [comment]
Why not, would be an awsome feature given the amount of brands that use 433 mhz

**Comment by bvdbos** [comment]
As then you also capture/copy noise at threat it like a signal...
