### ISSUE TITLE
Time-Tag is 1 minute behind

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1315]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Reading time from Tag

**What was the result?**

Time in tag is one minute behind compared to Homeys system time

**What did you expect as result?**

The tag shows the same time as Homeys system time

**Any other remarks**

...

**Comment by irritanterik** [comment]
Works ok for me on 1.1.4.

**Comment by OpenMindNL** [comment]
https://forum.athom.com/discussion/2718/time-tag-in-desktop-app-is-1-minute-behind

**Comment by chrisboer** [comment]
Resolved in 1.1.9

**Comment by bvdbos** [comment]
Not for me on 1.1.9:
20-2-2017 17:00:32.786	Speech-output	Speech	{"text":"het is 16:59 ","type":"say","session":"homey"}
with this flow:
![2017-02-20 17_41_49- 336 flow - homey](https://cloud.githubusercontent.com/assets/1064079/23134114/e439dc14-f793-11e6-9c23-5168080f9c0e.png)

**Comment by OpenMindNL** [comment]
Problem seems to be gone after 1.1.9 update.

At this moment I see the time-tag being updated 9 seconds after Homey's  date_human shows a new minute.

**Comment by OpenMindNL** [comment]
![homey-time](https://cloud.githubusercontent.com/assets/24574832/23134817/791aaac8-f796-11e6-89b6-b64aa2a2a330.jpg)

**Comment by nklerk** [comment]
Why is this issue closed? Running into the same issue (homey v1.3.0-rc.7)

**Comment by nklerk** [comment]
Wow thats fast :-)

Here is an example:
![example](https://cloud.githubusercontent.com/assets/16436184/26348436/09bb9d54-3fad-11e7-952f-e67d8b5380db.png)

when it just became 10 o'clock the flow is triggered but the tag is still at 9:59 so homey say's: "It's now 9 o'clock"

Up until now i allways used the tag from the "every hour" event card. ( card From the early days) and left it because it was just working perfectly. now i have changed it to the general time tag and found this.

**Comment by JPe2** [comment]
Sorry but even on Homey v1.5.0-rc2 this problem is not solved :# 
I've made a flow that starts every hour, after 55 second this flow starts a second flow that tells me the time, works well, but this should not be necessary.

**Comment by Tiyrell** [comment]
When Letting Homey say the Time using the $Time variable each minute, you have to delay the Speech by 35 seconds to tell the correct minute.
for instance, date_human flips to 13:15
Homey will say that the time is 13:

So:
Each minute > Say ($Time) (Delayed by 35 seconds)
Will work, but this is ofcourse not what you would want, a delay of more than 50% of the time we want to tell.

**Comment by WeeJeWel** [comment]
Yes, this is a known issue and on our list to fix!

**Comment by WeeJeWel** [comment]
I've changed some behavior in the upcoming 1.5.0-rc.6 release. Please let me know whether this issue still persist.

**Comment by JPe2** [comment]
It looks good now, I had a flow running that at every hour +0 +10 +20 +30 +40 +50 +59 sec. makes a logging, before I had a delay of 50 seconds to speak the time because sometimes it took more then 40 seconds before the right Hour was spoken. Now in rc.6 it looks ok (from 18-08-2017)
18-08-2017  ||  09:00:58  ||  +59 09:00 
18-08-2017  ||  09:00:50  ||  18-08-2017 09:00 Homey zei: het is: 09:00
18-08-2017  ||  09:00:40  ||  +40 09:00
18-08-2017  ||  09:00:30  ||  +30 09:00
18-08-2017  ||  09:00:20  ||  +20 09:00
18-08-2017  ||  09:00:10  ||  +10 09:00
18-08-2017  ||  09:00:00  ||  +00 09:00 Elk uur
18-08-2017  ||  08:00:58  ||  +59 08:00 
18-08-2017  ||  08:00:50  ||  18-08-2017 08:00 Homey zei: het is: 08:00
18-08-2017  ||  08:00:40  ||  +40 08:00
18-08-2017  ||  08:00:30  ||  +30 08:00
18-08-2017  ||  08:00:20  ||  +20 08:00
18-08-2017  ||  08:00:10  ||  +10 08:00
18-08-2017  ||  08:00:00  ||  +00 08:00 Elk uur

17-08-2017  ||  19:00:58  ||  +59 19:00 
17-08-2017  ||  19:00:50  ||  17-08-2017 19:00 Homey zei: het is: 19:00
17-08-2017  ||  19:00:40  ||  +40 19:00
17-08-2017  ||  19:00:30  ||  +30 19:00
17-08-2017  ||  19:00:20  ||  +20 18:59
17-08-2017  ||  19:00:10  ||  +10 18:59
17-08-2017  ||  19:00:00  ||  +00 18:59 Elk uur
17-08-2017  ||  18:00:58  ||  +59 18:00 
17-08-2017  ||  18:00:50  ||  17-08-2017 18:00 Homey zei: het is: 18:00
17-08-2017  ||  18:00:40  ||  +40 18:00
17-08-2017  ||  18:00:30  ||  +30 18:00
17-08-2017  ||  18:00:20  ||  +20 17:59
17-08-2017  ||  18:00:10  ||  +10 17:59
17-08-2017  ||  18:00:00  ||  +00 17:59 Elk uur

**Comment by WeeJeWel** [comment]
Great!
