### ISSUE TITLE
Homey speaker doesn't work when jack plug is used

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1368]
**What is your Homey version (Settings → System)?**

1.2.0 RC8

**What did you try to achieve?**
For music playback I need to connect Homey with a Jack Plug. This means that when my receiver is switched off I need to disconnect the Jack plug or I won't hear Homey until I switch on my receiver once again (could be the next week).

The user needs to have the option to select if he wants to use the Homey speaker for Homey's voice or use the loudspeakers. If not, Music would be almost worthless.

**What was the result?**

I can't hear Homey when my receiver is off.

**What did you expect as result?**

Homey's voice as a default over it's own speaker.

**Comment by AJediIAm** [comment]
I agree with this feature request. I don't want to have my whole audio system turned on all the time for speech. A portable speaker or Chromecast can both serve as a work around, but being able to set choose to use the internal speaker for voice would be a nice enhancement.

**Comment by TheMSB** [comment]
The usage described by @AJediIAm is the currently intended usage. When homey is connected to line out it is expected that all audio goes through it. Since Homey cannot detect if the line out connected speaker is turned on or not there is no automatic switching possible.

Currently there are no plans to support this feature so the recommended usage would be to use a Chrome cast audio to hook up your sound system to Homey.

Since Athom is constantly devoted to creating the best possible experience we may choose to implement this feature in the future when more pressing issues have been resolved.

**Comment by bvdbos** [comment]
Well, not entirely accurate... When playing music through the media without the jack connected, the webinterface states this is not possible. So Homey differentiates between voice and music, internal speaker and jack-output. But I know there are people who want Homey Voice redirected to the speaker and I for one want Homey music redirected to Homey internal (for radio 1 and audiobooks)...

**Comment by SailingDuck** [comment]
I have the same problem. Like whem I'm using Chromecast to watch Netflix, my receiver is using a different input. Or worse, my receiver could be turned off.  
Would be nice to have an alternative Speech card which is always using Homey's internal speaker when talking.

**Comment by basdejongg** [comment]
i agree that there should be an option to choose the speach output (line out, bt speaker or internal speaker).

**Comment by WeeJeWel** [comment]
This functionality won't be added to keep things simple, so I'm closing this issue.

**Comment by bvdbos** [comment]
somewhat related (and also closed): https://github.com/athombv/homey/issues/1471
