### ISSUE TITLE
music to chromecast: invalid_capability

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#1373]
**What is your Homey version (Settings → System)?**

Homey 1.2.0-rc.8

Google music v1.0.2
Google chromecast v2.2.3 for chromecast v1

**What did you try to achieve?**

Play a song from google music to google chromecast via the homey music app

**What was the result?**

An error appears stating "invalid_capability".
I was able to make a song play via the search bar and pressing enter, but it stopped half way. Clicking play again resulted in the same error.

**What did you expect as result?**

The song would play normally

**Any other remarks**

![capture](https://cloud.githubusercontent.com/assets/5879533/24122571/a50079ba-0dbc-11e7-98ca-5ac91b66ce72.PNG)

**Comment by caseda** [comment]
you need to re-pair your chromecast in the beta version of the app.

**Comment by AJediIAm** [comment]
Thanks for the tip. I will try it tomorrow.

It is definitely not the first time I needed to re-pair a device. Would it be possible to add a device version number and an indicator when re-pairing would be needed or recommended? A re-pair button would be very nice to have as well because preemptively re-pairing a build in device is a pain.

**Comment by caseda** [comment]
It is not always easy to say if people need to re-include.
It doesn't happen often anymore that a re-pair is required to keep an app working normally, media is a little different in this case. 

But in general if it has to do with capabilities (new or in very weird cases removed on) you will most likely need to re add your device since the capabilities used are defined when including the device. 
Chromecast's new capabilities now is the controls (play, stop, next, etc) which are needed in media. 

There will come a re-pair button in the future but it is not that easy to implement with the amount of different devices that all work a little bit different.

**Comment by bvdbos** [comment]
Well, re-pairing is #899

**Comment by AJediIAm** [comment]
Sorry that the discussion deviated from the actual bug. I will test the repair solution this evening and close the issue if it is solved.

**Comment by Amelsfort** [comment]
Re-pairing seems to work for me.

**Comment by AJediIAm** [comment]
Yes, repairing fixed the issue. Thanks for the support.
