### ISSUE TITLE
Sonos playlist not updated in music

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1374]
**What is your Homey version (Settings → System)?**
v1.2 RC8
Sonos beta v2.2.1

**What did you try to achieve?**
Update Sonos Playlist

*Please include detailed steps how we can reproduce the issue*
Added new playlist but not visible in homey 
Added one number to existing playlist not visible in homey

**What was the result?**
Playlist not updated

**What did you expect as result?**
New added playlist to be available under music / sonos
New added number in existing playlist to be visable under music / sonos

**Any other remarks**

...

**Comment by Qx5** [comment]
I also don't see the Homey Music playlists (so generated in homey music).
In the play playlist flow widget I only see my spotify playlists.

**Comment by BasKiers** [comment]
Hi, 

It is not possible to update playlists realtime. What I did add is polling for playlist updates every hour  and every time you select a Sonos speaker as active speaker. I hope this is the best tradeoff between flexibility and performance since updating all playlists is resource intensive. These changes can be found in the Sonos app version 2.2.2.

Regards,
Bas
