### ISSUE TITLE
Speech commands run personal flows AND internal actions at the same time.

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1389]
**What is your Homey version (Settings → System)?**

1.2.0-rc.8

**What did you try to achieve?**

I have a sea-salt 'crystal' with build-in bulb to warm the thing so that salt crystals are dispersed in the air.
I call this light 'Zoutlampje' and have few flows to switch it on/off by saying 'OK Homey... Zoutlampje aan/uit'

*Please include detailed steps how we can reproduce the issue*

Name a light 'zoutlampje' and create flows to check for the words "Zout" and "aan" or "uit", and make it switch the light by saying the commands.

**What was the result?**

ALL the lights in ALL rooms are switched on or off.... and the zoutlampje-flows are running too (Homey's voice response is saying "Het zoutlampje is ingeschakeld")

...

**What did you expect as result?**

...I expected only the "zoutlampje" to switch on or of.

**Any other remarks**

...

**Comment by Tweake** [comment]
System command are supposed to still trigger even when a flow is triggered. However, in your specific case the lights should not have been triggered, so I have fixed that. Additionally, I have added a confirmation before switching all the lights because it can be quite frustrating when all the lights in the house accidentally get switched on.
