### ISSUE TITLE
Cannot add Zwave Aeotec MultiSensor 6 - 2 errormessages and one window which shouldn't appear after an error

### ISSUE THREAD

**Issue by athomey** [athombv/homey#14]
I start pairing in Homey. I press Zwave button for Aeotec. Immediately thereafter Homey finds the sensor. Then says 'Interviewing device 1 of 1'. After a while the following error appears in a pop-up outside of the browser: 

>>> I'm sorry but 1 device could not be added. Please ex- and include these devices.Error nodes: 5

Then a secondary bug happens (so your flow is also not monkeyproof in case of error). A window appears "Which class is this?" as a title, with in it "Adding device".  nothing seems to happen.

Then a third bug happens, after a while (minute? two minutes?) an external browser pop-up appears telling me "invalid token"

About excluding and including? What does it mean? The device is excluded from Vera, according to the Vera wizard I walked through, and excluding from Homey is not an option, cause I never got it included due to these errormessages and such.

I close the external and internal dialogs, and then Homey seems to be ok, but my device is not added, and thus not usable. :-(

**Comment by athomey** [comment]
Still trying, resetting device, going back and forth in the UI of Homey. Still not working, but now the Follow the instructions seems to hang. Every time. The button 'Cancel' doesn't even do anything. The hint for 'Cancel' by the way, says "Cancel the addNode precess." that has a language tyope AND is a bit low-level using 'addNode' als a word. Gonna reset Homey now.

**Comment by ocatie** [comment]
The error message means that your device is added to the Z-Wave network but a problem occurred during the interview. The interview failed (my guess would be a dropped frame if the error occurs sporadically) so you get the message "Please exclude and include the device". The 5 is the assigned node id in the network. Because the sensor is added to the Z-Wave network you can exclude the device via Settings -> Z-Wave -> Remove Node because the inclusion did finish.

The window 'Choose class' is the next step after the interview and should indeed not show. My guess would be some leftover code from experimenting with critical and non critical errors.

The invalid token pop-up should be fixed in last update.

**Comment by athomey** [comment]
Thx. Clear. I tried "Remove nodig" and got some error I couldn't write down. When I press it the second time, I get and external of Chrome pop-up: "Unhandled errorremoveNode already running!". So what do I do now?

Also in the dropdown in the setting below, I cannot see a device there with Node (5), but I guess "Remove node" is for deleting added Nodes, which don't have a corresponding device in Homey, and "Failed" is for devices which are known in Homey as a node AND as a device? Am I right?

**Comment by ocatie** [comment]
The error means the exclusion process is already running, possibly in another session. Currently no check is preformed if there is already a exclusion session running. Put the device in learnmode or await the timeout to finish the current session.

The dropdown only lists the Z-Wave devices added to Homey (I'll add nodes in the network but not to Homey later). The remove/replace failed node feature should only be used for ghost nodes (not responding node id's). Your device is still responding but not added to Homey because the pairing failed (the Z-Wave inclusion succeeded).

You can use the upper Remove Node button to remove the device from the network. This resets the node id in the device to 0 and removes the Homey device if any (in this case there is no Homey device). When the device is removed from the network you can try to add it again using the pairing wizard.

**Comment by ocatie** [comment]
The Choose class window wasn't being closed properly upon an error. Working on fix.

**Comment by ocatie** [comment]
Fixed in next update
