### ISSUE TITLE
Homey should warn if a flow conflicts with an existing flow

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#142]
If you create your own flow "Turn on the lights" that conflicts with the build in one. But there is no way to know that as a user, as there is no feedback on this. There also is no list of available commands that you can access.

When creating a new flow, Homey should warn that the flow will conflict with an existing flow, no matter if that flow is pre-programmed or user defined.

**Comment by bvdbos** [comment]
There's use-cases when you want to start multiple flows with one trigger (ie when it starts raining) so I would vote against this. However: I think it should be possible to disable flows in the ui (both the built-in flows -Did you try "shut up"- and teh custom flows).

**Comment by AndreSomers** [comment]
Warn is not "block". 

I am not sure by the how voice commands are matched. Will Homey try every flow, or will it stop trying once it has found a match?

**Comment by Tweake** [comment]
Thank you for your suggestion. I am working on showing a warning message when you add a custom speech Flow trigger which interferes with Homey's built-in speech commands. We will not add a warning for conflicting custom speech Flows, because it's up to the user to manage their own Flows.

I am planning to have the warning added in Homey version 1.3.x, with a little luck 1.2.x
