### ISSUE TITLE
Homey runs personal flows but responds that it doesn't understand.

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1425]
**What is your Homey version (Settings → System)?**

1.2.0 rc10

**What did you try to achieve?**

Running my personal voice controlled flows

**What was the result?**

... They run, but Homey tells me "Ik begrijp niet wat je bedoeld"

**What did you expect as result?**

... Run the flows and don't tell me that it didn't understand.

**Any other remarks**

...

**Comment by Dijker** [comment]
Same question was on Slack yesterday

This was discussed at the Developer Preview channel, 
As this is channel is not available for everyone and slack conversations disappear over time, 
here the qoutes:

`robert [8:22 PM] `
`I have added that feedback intentionally, to let people know Homey heard something, but wasn't sure what to do with it. What custom command is it interfering with for you? You should not hear it if a flow has been triggered (edited) `
`[8:24]  
And I added the lights confirmation because we were getting too many complaints about all the lights switching when Homey did not hear a zone name correctly. Jsut say "turn off all the lights" to bypass the confirmation `
`Instead of this .... `
![image](https://cloud.githubusercontent.com/assets/12412734/24469090/ad23811e-14ba-11e7-8804-509d73dbf84c.png)

`try this:)`
![image](https://cloud.githubusercontent.com/assets/12412734/24469104/ba24ce4a-14ba-11e7-965c-ee617ec75976.png)

`swttt [8:46 PM] `
`@robert  what if i want to match 2 words said random in a setence?`
`weejewel [8:47 PM] `
`The order is ignored with this card`

**Comment by OpenMindNL** [comment]
"Something specific was said" is very user-unfriendly. This would require users to use exact commands instead of using a few words in a personal way.

**Comment by OpenMindNL** [comment]
I already had my own flows to make clear that a command wasn't understood. This only required me to make Homey say something when a command was recognized. When there was no Homey-response within 6 seconds after Homey stopped listening, it would tell me that it didn't understand the command. 
This worked fine but is totally messed up now.

**Comment by Dijker** [comment]
@OpenMindNL 
Correct, as #1425, the title is probably not correct anymore, 

on Slack the question `So if all those words are present in a sentence it should trigger? No matter what order or if other words are in between them?` 
was confirmed by @WeeJeWel !

**Comment by OpenMindNL** [comment]
So... "Something specific was said" would replace multiple "#text contains" ?

At this moment al my flows use two "text contains" to start an action. 1 for identifier and 1 for command, and the user could use any sentence as long as it contained these two words.
I could replace this with "Something specific was said" + the two words in any order?

Just asking because I tried this a few firmwares ago and it did not work.

**Comment by Dijker** [comment]
Sorry, I didn't test that jet, but I think you are correct and  this should make it easier....

**Comment by OpenMindNL** [comment]
Ok. Thanks for the response. 
I think I will wait for an official Athom response before I start changing all my flows. After all we're still in beta. ;-)

**Comment by WeeJeWel** [comment]
Yes, you should use 'Something specific was said' instead. When all of the words matched, not in that particular order, the trigger fires.

We will communicate changes like this more clearly in the future.
