### ISSUE TITLE
Autocomplete scenes card in Homewizard app stopped working after 1.2.0 rc9 & rc10

### ISSUE THREAD

**Issue by spoelly** [athombv/homey#1430]
**What is your Homey version (Settings → System)?**

1.2.0rc9 & rc10

**What did you try to achieve?**
Adding a scene with the Homewizard app.
*Please include detailed steps how we can reproduce the issue*
- create a flow
- add a if trigger
- add a then trigger (homewizard scene)

**What was the result?**
Normally the scene box has a search option when typing a word it will search for kwown scenes.
In 1.1.9 firmware this works after rc9 and rc10 not any more.

**What did you expect as result?**
See above

**Any other remarks**
An issue was also posted on the homewizard app github, but the developer of the app advised me to post a issue here also.
https://github.com/jeroenbos22/com.homewizard/issues/12#issuecomment-289454399

**Comment by jeroenvollenbrock** [comment]
This is a bug in the homewizard app.
Developer info:
https://github.com/jeroenbos22/com.homewizard/blob/master/includes/homewizard.js#L110 checks for explicit null values, while https://github.com/jeroenbos22/com.homewizard/blob/master/includes/homewizard.js#L77 returns false as error. Please return a valid instance of Error instead of false upon errors, and check if the err argument is truthy. If the error argument is falsy, an array is required as second argument.

**Comment by jtebbens** [comment]
Bug is fixed in Homewizard app v.0.1.3 and up
