### ISSUE TITLE
Speech command lights off livingroom not working

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1436]
**What is your Homey version (Settings → System)?**
1.2.0 rc10

**What did you try to achieve?**
Put out the lights in the living room by the speech command "Homey zet de verlichting uit in de woonkamer" 

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24568728/55f9af30-1663-11e7-96e8-d56109d972f7.png)

**What was the result?**
Homey answers it can not find any light devices in "de woonkamer" ... I don't know but I see 4 light devices in the livingroom.

**What did you expect as result?**
That homey would have put out the lights in the livingroom
...

**Any other remarks**

...

**Comment by Tweake** [comment]
Thanks for providing a screenshot. The issue is occurring because you have devices (which are not lights) with a name similar to the Zone name.

Device names are prioritised over Zone names. When Homey detects a device name it only focusses on that device and ignores all other devices in the Zone with the same or similar name.

Let's say you currently have some lights in the Zone "living room" and a Chromecast also named "living room". When you say "turn on the light in the living room" Homey detects a device name 'thinks' I should turn on the light of this specific device which was mentioned. After Homey starts switching on the light of your Chromecast it realises that this is not possible. So, no lights end up switching.

To prevent this from happening, from version 1.2.0 on Homey will give a warning when you rename a device to something which conflicts with a Zone name. Previously added devices are not checked though, which is why you are experiencing this issue. Renaming the devices should resolve your issue.

On the plus side, you can now reference specific devices by name!

**Comment by chrisboer** [comment]
Renamed the devices but turning on works but turning off is not working

**Comment by chrisboer** [comment]
disabled 2 flows 
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24652069/92196f8a-1930-11e7-8428-dc96235f22e6.png)

**Comment by chrisboer** [comment]
Different problem occurs now, not all the lights go on, one light is not turned on or off 

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24652173/149bbe54-1931-11e7-87cc-3919cef181d9.png)

**Comment by chrisboer** [comment]
The device was not going on or off because another "speech flow" was triggered an so homey broke of the general command and started to execute the other flow. 

Problems solved now.
