### ISSUE TITLE
[Speech] Parser not smart enough

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#1458]
**What is your Homey version (Settings → System)?**

1.2.0-rc10

**What did you try to achieve?**

I tried closing the shutter by saying 'doe het rolluik in de keuken omlaag' (I also used speech-input, see screenshot below)

**What was the result?**

Homey told me he couldn't find the shutter

**What did you expect as result?**

The correct shutter closing

**Any other remarks**

As you can see, for some reason Homey was looking for 'het rolluik' which, of course, isn't an existing device (the device is named 'rolluik keuken')
When I simplify the command it works, but this isn't natural speech, and I would expect Homey to understand a regular simple sentence.

![rolluiken](https://cloud.githubusercontent.com/assets/1757287/24741651/2c98aef0-1aa7-11e7-9c44-609eaabdc899.png)

[edit]
Also, I would expect it to reply that the 'rolluik' is being closed, not 'zonwering' since I was closing it in the evening when there is no sun :-P

**Comment by Dijker** [comment]
Do you have an other Device named "Keuken" like an switch, light or .... (anything, thermostat, Chromecast etc)

**Comment by Fire69** [comment]
Yes, the light in the kitchen is named 'keuken'.
I changed it to 'licht keuken', now the shutter command works correctly.

Not very logical in my opinion.  The 'rolluik keuken' has the shutter capability I suppose, so I don't see why the name has anything to do with it.

**Comment by Dijker** [comment]
Yesterday at the Dev Meetup in Utrecht Robert explained the Speech Parser....
I guess it is smarter than you expect .... 

I I am correct: "in de" before Keuken makes Keuken the location. from 1.2.0 (tested rc11)  Homey will warn you not to  name devices the same as the zone as Homey will first look for devices you mention an then for the zones.

![image](https://cloud.githubusercontent.com/assets/12412734/24743719/93857ef6-1aaf-11e7-9941-6d418ec8bebe.png)

**Comment by Fire69** [comment]
I expected it to work with my current naming, so it's not smarter then I expected :)

If it takes Keuken as location (which seems logical), and the command asks to close a shutter, shouldn't it be smart enough to close any shutter in that zone?

But it's ok like this, I renamed my lights to include 'licht' in the name and it's working as expected now :)

**Comment by Tweake** [comment]
The issue you were experiencing is caused by the fact that device names can be anything, which makes it more likely that the STT parser does not detect it 100% correctly. For example, if you have a device named "stalamp" you also want it to be found when the STT parser detects "sta lamp". To make sure device detection works we allow for some noise in the name. In your case "in de" was considered noise and the zone name was considered to be a device. To prevent this from happening we have added the warning when renaming a device, like Dijker posted. Unfortunately this only works for newly added devices. 

As for adding "licht" to all your devices, this should not be necessary. Let's say you have a licht named "bijzettafel", you could just say "bijzettafel aan". If this is not working well for you I'd like to look into that by seeing your zone names and device names.

**Comment by Fire69** [comment]
Did some tests again (since I'm now at 1.3rc7), and whether I name the it 'Keuken' or 'Rolluik Keuken', both are working correctly now so I guess the issue is resolved. :
Maybe just change the response to something more natural? 'Ik zal rolluik openen' sounds weird :)

**Comment by Tweake** [comment]
Glad to hear the issue is resolved. 

Rephrasing the response is on my todo list. Dutch is not an easy language for quickly generating pretty responses, due to the "lidwoorden" and changes to the phrase due to plurality. As a result there are other tasks which offer more benefits for the time invested. I will get to it in the future though.

**Comment by Fire69** [comment]
Don't want to reopen this for now, but I was just struggling with this again.  Did something change since 1.3rc7?
So I have a zone 'Keuken', in that zone I have a light and a shutter.  Since those are the only devices in that zone, they were also both called 'Keuken'.  I know it's not recommended, but what should I call them then?
Anyway, I couldn't control the shutter anymore again. No matter what voice command I tried, nothing worked.
I renamed the shutter to 'Rolluik Keuken', no change.  I always got 'Ik kon geen rolluik vinden om aan te sturen'.
Then I renamed the light to 'Licht Keuken' and the problem was solved.
When I rename both to 'Licht' and 'Rolluik' it's working OK also.

So I guess either a solution for the naming should be found, or maybe you should just prevent devices from being named the same as the zone? (instead of warning users that it might cause problems)
