### ISSUE TITLE
rf-connect from the company Merten ( know its called Schneider doesn't work )

### ISSUE THREAD

**Issue by blurkie** [athombv/homey#1477]
**What is your Homey version (Settings → System)?**

1.2.0

**What did you try to achieve?**

All the components comming from the company Merten( now it s called Schneider) doesnt work properly.
They have a lot of z-wave products. called rf-connect. 
I can use this components in all kind of z-wave gateways but in Homey it doesnt work.

**Comment by jeroenvollenbrock** [comment]
Can you be a bit more specific as to what doesn't work, and what steps you have taken to try to get it to work? Is it possible to pair the product? Do you get any errors?

**Comment by blurkie** [comment]
You can pair the product but a product like a dimmer is a switch in Homey. So you can t use it like a dimmer. 

Met vriendelijke groet,
Arjen Mertens

**Comment by jeroenvollenbrock** [comment]
This is because homey only support basic on/off control for devices that have no app. I've added the brand to our requested device support list, but it does not have a very high priority yet compared to other devices. You could also try to see if anyone in the community is interested in creating a Homey app for you. You can get in contact with them via the [forum](https://forum.athom.com) or [slack](https://slack.athom.com)

**Comment by WeeJeWel** [comment]
Please contact support@athom.com with your Device support request, or ask a developer on the Forum (https://forum.athom.com) to create an app for this brand.
