### ISSUE TITLE
[Z-Wave] Not all flow cards available when device is included as Light device/class.

### ISSUE THREAD

**Issue by SkorpionNL** [athombv/homey#1501]
**What is your Homey version (Settings → System)?**

1.2.2 stable

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

I wanted to use scene flow cards i.c.w. a Fibaro FGS-223 for Q1 that was included in Homey as a light. 

**What was the result?**
Because Q1 was added as a light device/class, the scene flow cards weren't available. I had to re-include the device and Q1 as "another device attached" in stead of a light to make the scene cards available.
...

**What did you expect as result?**
To have scene flow cards available for devices that were included as light for example.

...

**Comment by caseda** [comment]
Just as added information:
The flow cards are invisible because they are bound to a _Custom Capability_
(the easiest way to disable them for a child note where they don't work)

So the Custom Capability is being hidden when being in a for example `Socket: Light` class
They do show up in the normal "Socket" class
