### ISSUE TITLE
Unable to install beta release app from appstore and cli

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1508]
**What is your Homey version (Settings → System)?**

1.3.0-rc2

**What did you try to achieve?**

install the magister 2.0.0-beta1 app from the appstore and from the local cli.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
![2017-04-25 1](https://cloud.githubusercontent.com/assets/19174120/25393960/3685d934-29dd-11e7-8061-284b776e9478.png)

...

**What did you expect as result?**

...

**Any other remarks**

I installed the exact same version from the appstore a week ago without a problem. Something changed in the mean time. It also doesn't work anymore from the cli. I can change the versioning to not include the -beta1 part, but that would really mess up my version naming....
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
We have indeed made changes so that pre-release versions for apps are not allowed.

The library we use, node-semver, is very buggy when it comes to comparing versions with prerelease tags. We've head our headaches with Homey itself already, so we'd rather avoid the same hassle with apps.

Sorry for the inconvenience, but it's for a more stable cause :)
