### ISSUE TITLE
Speech Command switch all Philips Hue light on not working

### ISSUE THREAD

**Issue by admaawe** [athombv/homey#1532]
**What is your Homey version (Settings → System)?**

1.2.2

Speech Command switch all Philips Hue light on
 1 - first try to switch on my Hue lights
Okay Homey "lichten aan" 
Okay Homey "lampen aan"

1 - Result: "licht kan niet worden geschakeld" 

2 - first try to switch off my Hue lights
Okay Homey "lichten uit" 
Okay Homey "lampen uit"

2 - Result: "licht kan niet worden geschakeld" 

What did you expect as result?

I expect this key feature to work.

...

- I Reinstalled the Hue app and rebooted the Homey same result
- I created a (work a round )flow witch switch off all the lights by voice and it worked.
- It had worked before but I noticed that the Hue App is very unstable crashes almost daily.

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
 log code 5AE6025464

Kind regards,
Idude
...

**Comment by Tweake** [comment]
Thanks for creating the issue and including a log.

Based on the logs I can see that Homey does detect your request correctly. However, in 1.2.0 I have added a confirmation when switching the lights without specifying a zone or device. This was added to prevent unfortunate situations where a person would say "turn on the lights in the living room" but the zone name was not detected correctly, so the lights get turned on in the entire house, including a bedroom where someone is trying to sleep.

I suspect you did not hear Homey ask you "Wil je echt dat ik alle lichten aan zet?" after each time you asked. If you respond to the question you will find that the lights switch as expected. Alternatively, you can bypass the question all together by saying "**all** lights (on/off)" instead of just "lights (on/off)"

**Comment by admaawe** [comment]
Hi Robert,


The Hue app is very unstable!

I have to restart the Hue and the Ring app for that matter on a daily base.

 
 


Met vriendelijke groet,
 
Wiard Engeman
Emailadres: w.engeman@virtual-me.nl mailto:wiard.engeman@virtual-it4you.nl

**Comment by tunf** [comment]
same issue here, sometimes homey asks, do you really want to turn all lights off, answer yes, homey tells me it cannot do the action, tried this with several persons and also in 1.3 rc7 it is there as an issue, beside that the hue lights often don't turn on or not all that schould be and for off the same.

**Comment by Tweake** [comment]
@admaawe Sorry to hear your are also having issues with the Hue app. Since that problem is not related to this voice command issue it's best to open a new ticket [here](https://github.com/athombv/nl.philips.hue/issues).

@tunf could you try saying the following and write down Homey's response for each of them? This will help me narrow down the issue you are experiencing. 
"turn on all the lights" (zet alle lampen aan)
"turn on the light in the <zone name>" (zet het licht aan in de <naam van een zone>) **Make sure there are connected lights in the zone and that they working when you toggle them manually**
"turn on <light name> (zet <naam van lamp> aan) **Make sure the lamp is connected and can be toggled manually**

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
