### ISSUE TITLE
Presence-notifications

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1561]
**What is your Homey version (Settings → System)?**
1.3rc7 and android app version 2.4.7 build 77

**What did you try to achieve?**
Use the new Presence, set 145 m area, use gps and don't use presence-notifications in the phone-app

*Please include detailed steps how we can reproduce the issue*
1) Just got home, the Homey app announced I "exited Homey home area". typo: exitted
2) I came home, why would Homey announce I exitted? Was first-time use of new presence...
3) My setting is no push-message but only turned on so only expected a notification in the UI
4) The notifications in the UI showed I got home, the "exitted" wasn't there (so like it should be...)
![2017-05-18 20_16_52- 653 settings - homey](https://cloud.githubusercontent.com/assets/1064079/26217340/4c95581c-3c07-11e7-8652-da46369a3145.png)

**Comment by bvdbos** [comment]
log 68F82E6911

Homey just thought I left the house... No notification on the phone, do have a notification in the UI.

**Comment by bvdbos** [comment]
This morning I went to walk the dog. My phone alerted me (Homey-notifications) I went away and came back correctly (still: notifications are turned off)... Homey UI only showed I came back (as Homey thought I went away last evening?).

insights-log:
Thu May 18 2017 19:35:34 GMT+0200 (CEST),true -> coming home from work
Thu May 18 2017 21:28:50 GMT+0200 (CEST),false -> set as away while I was home
Fri May 19 2017 07:04:16 GMT+0200 (CEST),true -> came back from walking the dog

Strange thing is the status of the notifications seems correct (apart from the first time) but presence in Homey-UI isn't?

**Comment by joachimroeleveld** [comment]
So for my clarity, you got the initial exit notification while the "Transition notifications" setting was disabled?

The other issue seems to be related to presence changes not being synchronised to the Homey UI notification center as you already indicated.

Could you maybe enable transition notifications to ensure the phone's notion of presence is correct? If these notifications are correct, it is an issue with Homey, otherwise with the app.

P.S. Exited is actually correct, as per [dictionary](https://simple.wiktionary.org/wiki/exit) ;)
