### ISSUE TITLE
Can't login to my Homey after a reboot. It's saying "unauthorized"

### ISSUE THREAD

**Issue by kanhetwel** [athombv/homey#1610]
Help! Can't login to my Homey after a reboot. It's saying "unauthorized"
Homey V1.3RC11

I Tied to PTP 4 times, and did a reset. Homey seems to be working properly flows an speech are working but I can't acces it witch any app or dashboard. and keeps telling i'm unauthorized.

**Comment by jeroenvollenbrock** [comment]
Hi, First of all, i'd like to apologize for this inconvenience. The reported issue is caused by a bug in the experimental version 1.3.0-rc.11 that could cause settings to become corrupt under certain conditions, and this bug has been resolved in 1.3.0-rc.12.

Unfortunately, this does not restore the already corrupted settings. Luckily, there are two ways to resolve this:
- Run Homey recovery by turning Homey upside down and choose `Reset to factory settings` (this will reset your homey to factory defaults and reset all settings)
- Contact us at `support@athom.com` (or chat with me directly using slack (https://slack.athom.com, @jeroenvollenbrock) to see if we can restore just the user settings for you.

**Comment by kanhetwel** [comment]
Problem solved by restoring a backup by Jeroen from Athom.  Thx!
