### ISSUE TITLE
"don't know what todo" after flow programmed speech 

### ISSUE THREAD

**Issue by Wijkie76** [athombv/homey#1614]
**What is your Homey version (Settings → System)?**

1.3.0-rc.11

**What did you try to achieve?**
Trigger a flow with a flow-programmed speech command.

I rpogrammed a flow. The flow should be speech triggerd by for ex. "bob saloon" cause that's what I programmed in the When colum. (When you say "bob saloon" then... etc etc.) 

**What was the result?**
It triggers the flow but Homey still says "i'm sorry i don't know what you would like me todo"
If the speechcommand isn't hardcoded in Homey or app, it gives the same result.
...

**What did you expect as result?**
Homey not saying "i'm sorry i don't know what you would like me todo"
...

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
39519E0478
...

**Comment by Tweake** [comment]
Hi @Wijkie76, could you please post a screenshot of the Flow? Thanks!

**Comment by Wijkie76** [comment]
![knipsel](https://user-images.githubusercontent.com/28150252/27344841-0bb0d362-55e8-11e7-878c-e3a747bff4ae.PNG)

**Comment by Wijkie76** [comment]
Saying "video on"  does trigger the flow

**Comment by Tweake** [comment]
Thank you for posting the screenshot. The issue is caused by the use of the when-card "Anything was said" in combination with the and-card where you check what the text was. If you replace the current when-card with the when-card "Something was said containing" and type _video on_ there, Homey should no longer say the message. You can find the "Something was said containing" card by using the arrows on the right side of the current "Anything was said" card

**Comment by Dijker** [comment]
@Tweake @WeeJeWel 
I guess Athom  wants to discourage the use of the anything was said card, 
I personally would like to keep it as a debug trigger but first time users and readers of the ferry old part of the forum still use it.

Could you add a warning to this card? Deprecated... and maybe to the flow list/tree?
See https://forum.athom.com/discussion/comment/56542/#Comment_56542
