### ISSUE TITLE
Animation speed is too fast when TFPS is not divisible by FPS

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1623]
**What is your Homey version (Settings → System)?**

1.3.0

**What did you try to achieve?**

I created an animation with 44 frames and registred it with these parameters:
priority: 'INFORMATIVE'
duration: 40000
options: { fps: 22, tfps: 60, rpm: 0 }

**What was the result?**

Animation was running too fast. Something like 1.5-2x

**What did you expect as result?**

One cycle every 2 seconds.

**Any other remarks**

I tried again with these options:
options: { fps: 22, tfps: 44, rpm: 0 }
Speed was perfect, just like with
options: { fps: 22, tfps: 22, rpm: 0 }

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by jeroenvollenbrock** [comment]
TFPS must always be divisible by FPS, in order to avoid aliasing issues. I've updated the docs to mention this more clearly. When TFPS is not divisible by FPS, the FPS is rounded up till the closest divisible value. I've set this issue to be an enhancement to see if we can round TFPS up instead, as this will probably resemble the developers intention better.

**Comment by OpenMindNL** [comment]
Didn't notice there was response on this one.
I can understand that this one is not important, but I disagree about the aliasing. This could be solved with higher internal clocks.... the internal clock should be divisible by FPS and TFPS... that would solve it I think?

**Comment by OpenMindNL** [comment]
Just a thought...
In LEDitor I tricked this issue by calculating how many ms a frame-change (FPS) takes... and the same for the Interpolation (TFPS) for the on-screen animation.
The animation-loop now checks these two intervals and performs the change when needed.
In LEDitor the TFPS are simulated by changing the opacity for a top-canvas that contains current frame, so the below-canvas that contains the next frame becomes visible in TFPS-intervals.

Another thought:
Let's make things complicated.... we run an animation @ 13 FPS and we want 60 TFPS.
To get an animation without aliasing, we would need to calculate 780 new frames that contain the interpolated color changes inbetween the real frames.
Of course it would be crazy to make Homey run animations at 780 FPS.... so we take every 13th frame from this cycle to create a new batch of frames.... 60 frames that contain the 13FPS animation incl. interpolations.... if my thoughts are not wrong....

**Comment by OpenMindNL** [comment]
Oh... and please... don't round up TFPS. I see the advantage for a developer, but for an artist it's like taking away a tool that can be used for nice effects 😎

**Comment by jeroenvollenbrock** [comment]
Hi @OpenMindNL. The Problem with this, is that this is only possible if the the rpm matches the same state in the same frames every rotation, and if two succeeding different animations always have the same rpm, because the keyframes are no longer being rendered as actual frames. As soon as this is not the case, all non key-frames will have to be calculated and rendered on the fly. I've modified the code a bit to round up the tfps to the nearest available multiple of fps, instead of rounding fps down to the nearest available value that has a tfps multiple. This makes sure the fps and rpm are always being met instead of the tfps being always met. Ofcourse you can still set tfps = fps if you dont want any interpolation to occur. In your case of the 13fps/60tfps this will result in an actual of 13fps/65tfps, instead of 10fps/60tfps which is what happened up until now. The difference between 13/65 and 13/60 should be barely indistinguishable.

**Comment by OpenMindNL** [comment]
Sounds acceptable @jeroenvollenbrock . Let's see how it works.

**Comment by jeroenvollenbrock** [comment]
Staged for release  in https://github.com/athombv/homey-linux-kernel/commit/396bdf597b77f3fd7c03849945761110844586e8
