### ISSUE TITLE
fibaro wall plug fails after a couple of times switching

### ISSUE THREAD

**Issue by kingdong78** [athombv/homey#163]
Fibaro wall plug is easily paired.
But after a couple of times of switching it is unreachable.
I reset the fiber wall plug but isn't removable from homey with remove nod or either remove failed node
homey software 0.8.17

**Comment by athomey** [comment]
Can you give reproduction steps? Where do you toggle, in a flow, device, on the hardware itself, etc.? I cannot reproduce your Fibaro Wall Plug problem. Thanks in advance for more details.

**Comment by ocatie** [comment]
If you factory reset your plug you'll end up with a ghost node in your network. Always remove devices using Settings -> Z-Wave -> Remove Node, and triple press the button on the plug upon the Present node message.

If a device becomes unreachable an overlay is displayed over the device. To remove the overlay and let your device send any data to Homey. Triple clicking the button on the plug might do the trick, or (in Settings -> Z-Wave) select the device in the dropdown and press Refresh Node.

In order to use the Remove Failed Node you have to verify it is unreachable first. You can do that by selecting your device in the dropdown and pressing the Refresh Node button. If the device is unreachable the refresh will not succeed and you'll be able to remove the (ghost) device using the Remove Failed Node button.

If you can provide more information I can reopen the issue.

**Comment by kingdong78** [comment]
I did the exact procedure you suggested and i can't remove it out of the z-wave network.

**Comment by kingdong78** [comment]
![schermafbeelding 2016-02-13 om 09 53 14](https://cloud.githubusercontent.com/assets/17185881/13026867/c217fd82-d237-11e5-87fe-55e5b57994c9.png)
![schermafbeelding 2016-02-13 om 09 54 49](https://cloud.githubusercontent.com/assets/17185881/13026868/e0f9cd7a-d237-11e5-8bf7-74cfb6e43975.png)
It says its running in another session what i am doing wrong

**Comment by athomey** [comment]
@kingdong78  It sounds a  bit like my unremovable device #167   even if I reboot and make sure zwave is not doing anything else, I cannot remove the ghost nodes (nor the ghost device).

**Comment by kingdong78** [comment]
yes it seems to be the same issue

**Comment by athomey** [comment]
Well, then @ocatie has **reproduction**: Add a Dimmer v2 | ignore the errors, cause an app will fix that as taco said | Remove node | wait long enough, ignore anything that happens | factory reset the device | Reboot Homey through the menu | Select in drop down with failed nodes | Refresh node | Remove failed node......then Ghost device + ghost node, cannot remove in any method I could think of. 

I did the prior thing twice with in between a factory reset of Homey with clearing all the data. Same problem again.
