### ISSUE TITLE
Trigger flow based on condition change

### ISSUE THREAD

**Issue by RobertMe** [athombv/homey#1647]
**What is your Homey version (Settings → System)?**

1.3.1

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

Creating complex flows based on multiple conditions. Like "When the sun is down, and the lux is below X, then turn on the lights" (optionally with "else turn them off")

**What was the result?**

I had two create two flows. One being triggered when the sun goes down, with the condition for lux below X, and another based on the lux change, and the lux being below X, and the sun being down. Which means having to duplicate the logic which is cumbersome when you have to change for example the lux threshold.

**What did you expect as result?**

Only having one flow.

**Any other remarks**

I've been brainstorming about an idea where you have a trigger "The condition has changed" which will then monitor all the condition/"and" cards, and when the end result changes (so true becoming false or the other way around) the then/else actions could be executed. Automatically evaluating conditions could then for example be based on the changes of the tags which are used as droptoken (on for example logic cards) or by changes in capabilities (as (almost) every condition card also has a trigger to detect the change in condition, and almost all of these conditions/triggers are backed by capabilities).

I understand this could lead to performance issues when having a lot of flows using this trigger, and possibly having multiple cards in them every time. But this could mostly be prevented by only monitoring the condition cards which where actually tested the first run. So when having three condition cards, these would be tested in order. So when the first card already is "false" this means only a "monitor" for the first card is needed (and when the first card is true, and the second is false, both need to be monitort etc). This because the other cards don't matter, as long as a previous card was false the end result will still be false (unless "or" is introduced, but then the same rule applies, only the tested cards need to be monitored).
Performance could be further improved by only retesting all conditions when the "changed" card actually changed. So for example when having a logic card which states "lux < 20" and first the lux is 30 (which evaluates to false) and then there is a lux change to for example 25 the card needs to be retested, but as the result is still false the other cards on the flow don't need to be retested because the outcome of this card, and thus flow, wouldn't have changed.

**Comment by Dijker** [comment]
Look at your insights how often the lux changes. Probably every couple of minutes depending on how you have placed  the sensor and it's sensitivity. 
Is so you could skip the if the sun goes Down trigger, the other will fire within minutes and the condition sun is down is true.
Result: one flow less and probably almost same result

**Comment by RobertMe** [comment]
Thanks for the answer, but it of course was just an example. And there are lots of other similar scenarios where you have multiple triggers/conditions and when all are satisfied then something should happen.

As a colleague and Homey user said to me today 'Do you want to build an AI with it?'. No, of course not. But currently the possibility to build more complex flows, with multiple conditions (and thus triggers), are way to restricted. Or indeed require building lots of flows with different triggers but applying the same conditions to them. Being able to simply run some action(s) based on whether a condition is satisfied (or not satisfied anymore for the else) would just greatly simplify it.

**Comment by bm480** [comment]
> Creating complex flows based on multiple conditions. Like "When the sun is down, and the lux is below X, then turn on the lights" (optionally with "else turn them off")

You could create a single flow based on the Sun Down event and compare the Lux-tag in the And-column. In order to execute the same functionality for multiple triggers, you could place this functionality in a separate flow which is triggered by a Flow Activated-trigger.

I think the flow functionality of Homey is intensionally kept simple in order to keep processing overhead to a minimum and the entry-level for (new) users fairly low. Most things can be accomplished by combining multiple flows, which isn't that bad. It is easy to duplicate a flow and creating a new one from scratch doesn't take much time. However, having a good naming scheme may come in handy. Especially when you have integrations consisting of 10 flows or more... Ever wondered why there is no Script-activity or Loop-activity? That is to prevent badly designed flows from clogging up your Homey.

**Comment by bm480** [comment]
Note that as a software developer you always strive to make things more efficient, for example by combining things into a single flow. This may seem most efficient in regard to creating and maintaining flows. But in regard to designing, testing and running flows it helps to keep things simple and straightforward. As developer you sometimes need to think another way in order to achieve your goals. As an example, I tried to create a state machine for monitoring progress of my washing machine and the solution ended up with 10 flows. I then rethought the design and discovered that actually there are only 3 states which made the solution much simpeler.

You should not look at Homey as a software platform, but more like it is a machine made out of nuts and bolts and creating the same type of solution again means that you need to put in another set of nuts and bolts.

**Comment by WeeJeWel** [comment]
This won't be added, because there simply should be a trigger 'when the sun went down' or 'when the lux is changed' (which there are if I'm not mistaken).

A condition is time-independent, by design.

**Comment by RobertMe** [comment]
"This flow is activated" also isn't time dependent. That's also why I stated that I would make this a "special" flow for which there is a trigger, "condition has changed", just like the flow activation cards. I didn't say that the triggers as a whole should be removed.

And time dependent conditions could of course also re-evaluate the condition as a whole when the time changes. As in the end there is no difference when you either have 1 flow:
**If** the condition changed **And** It's between 20:00 and 23:00 and lux is below 30 **Then**...
Or when you have 4 flows:
**If** this flow is activated **And** It's between 20:00 and 23:00 and lux is below 30 **Then** ...
**If** the time is 20:00 **Then** activate flow ...
**If** the time is 23:00 **Then** activate flow ...
**If** the lux changed **Then** activate flow ...

**Comment by Dijker** [comment]
@RobertMe 

> "This flow is activated" also isn't time dependent.

it is time dependent, it's event  is triggered once another flow executes the following action cards:
![image](https://user-images.githubusercontent.com/12412734/27838859-922a140c-60ed-11e7-9afc-061616948309.png)

all other triggers (When Cards) are already (singe) conditions that have changed. Call it Events or triggers.... 
but it isn't a condition. 
![image](https://user-images.githubusercontent.com/12412734/27838985-5221eaf0-60ee-11e7-982d-993870eb0011.png)

but if you create a flow that triggers every minute, and have the correct conditions.... 
only add a Countdowntimer for an hour (or 3) and add a if Timer not running.  (de-bouncer to prevent running every minute.)

Again one flow and the same result.
