### ISSUE TITLE
KaKU ACM-LV10 not working

### ISSUE THREAD

**Issue by Ziglar1** [athombv/homey#1650]
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.3.2

**What did you try to achieve?**
This morning, homey could communicate with the KaKu ACM-LV10, this evening not anymore.
i resetted the kaku and now i am trying to re-connect it to homey, when using the option "generate new signal" the kaku does not get connected.
Openmind_NL on slack also experienced some strange connection behavour with his kaku's

*Please include detailed steps how we can reproduce the issue*
disconnect a kaku (kaku acm-lv10 in my case) , reset the kaku and connect it to homey using "Generate new Signal" option.

**What was the result?**
the module did not connect.
...

**What did you expect as result?**
the module gets connected and can be dimmed 0~100% 
...

**Any other remarks**
KlikAanKlikUit v3.1.3
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

B54CDDB1C8

**Comment by Dijker** [comment]
@BasKiers  see the discussion here: https://forum.athom.com/discussion/comment/53601/#Comment_53601

ASUN-650 Blinds receive two (Interrupted) from one transmit from Homey
I also see an issue with the ASUN650 since last day, 
My blinds have worked perfect for  quite some time, 
since yesterday I see sometimes the ASUN interpreted one signal from Homey as a start and stop (within 2/3 seconds)
Maybe also change in the code changed the interval of repetitions?

**Comment by Ziglar1** [comment]
Problem resolved with KaKu Update
