### ISSUE TITLE
Confirmation not listening for yes/no

### ISSUE THREAD

**Issue by JerryVdV** [athombv/homey#1691]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**
Try to create a flow.
![image](https://user-images.githubusercontent.com/29510796/28437262-49f55cfa-6d9a-11e7-90d2-35bea7c036bf.png)

**What was the result?**
1) Homey does not listen for confirmation (i.e. no listening ring is visible, just the rainbow; no voice input can be seen)

**What did you expect as result?**

1) that Homey listens for speech confirmation 

**Any other remarks**

None.

**Please attach a Homey System log (Settings -> System -> Send Log)**

ED7650CAF5

**Comment by swttt** [comment]
I am not 100% sure (and not even sure if it's 100% related to your issue) and someone should correct me if i am wrong. 

But i thought that when all the 3 cards in the AND column (middle one) are valid, then it triggers the regular actions. And if only one of them is false, it should trigger ELSE part.

So in this case you might created some kind of loop:
If all 3 middle column cards are true, you set the variable so it triggers the same flow again. Since the washer variable now contains 'Empty' it runs the ELSE part.

**Comment by JerryVdV** [comment]
I think you're right. 
Then only the issue for (not) listening remains, adjusted the post.

**Comment by swttt** [comment]
actually this might be the same reason why the speech confirm isn't working...Even if your speech confirm is true, and one of the other ones is false. It would still trigger the else part. So maybe because of one of them being false already it asks but isn't listening afterwards.

**Comment by Dijker** [comment]
I tested your flow and I can confirm This isn't going to work as you expect ! ;-)
Had to test on Dutch as my Production is 1.3.2 and Dutch, and Dev is running 1.5 alpha  with the OR card and I have seen issues with them, so No English Homey to test.

![image](https://user-images.githubusercontent.com/12412734/28432717-4101de86-6d89-11e7-853f-ac229593e206.png)

Whenever I trigger Flow 1691b the Token Washer is set to Finished.
Both first two condition cards are True and Homey Asks Leeg?
When I see the Question (manager/speech-output/ ) and the Ring ligthing for a response I type Ja at (/manager/speech-input/) as I am to far away. The Then part Executes. 
At That moment the Flow triggers again (as it is a loop) and as Both first to conditions are False there is no change to get a True in the ...And... column. So the Else executes immediately. The Countdown timer starts. 

Point is: as te second time Homey should not ask for Confirmation (Leeg?) And I don't hear that or see it in Manager/Speech-Output 
but approx. 120 seconds after that I get the a "Het spijt me, maar ik begrijp niet wat je bedoelt "  and the confirmation I gave (Ja) from the Homey Flow: "Anything was Said"

Don't know what you expect from the Countdown and if you have an other flow to trigger on that? 

This is the trail: 
2017-07-20 21:00.17 Variabele Washer is: Finished 
2017-07-20 21:00.17 Homey zei: Leeg? 
2017-07-20 21:00.20 Test#1691 Then
2017-07-20 21:00.20 Homey zei: Goed! 
2017-07-20 21:00.20 Variabele Washer is: Empty 
2017-07-20 21:00.20 Test#1691 Else
2017-07-20 21:00.20 Countdown Washer gestart
2017-07-20 21:01.22 Countdown Washer leeg
2017-07-20 21:02.20 Er werd iets gezegd: ja 
2017-07-20 21:02.20 Homey zei: Het spijt me, maar ik begrijp niet wat je bedoelt 

and this is the Trail answering Nee on the Question and Homey now triggers only once of course. 
2017-07-20 21:07.30 Variabele Washer is: Finished 
2017-07-20 21:07.30 Homey zei: Leeg? 
2017-07-20 21:07.34 Test#1691 Else
2017-07-20 21:07.34 Countdown Washer gestart
2017-07-20 21:08.38 Countdown Washer leeg
2017-07-20 21:09.35 Er werd iets gezegd: nee 
2017-07-20 21:09.36 Homey zei: Het spijt me, maar ik begrijp niet wat je bedoelt

**Comment by Dijker** [comment]
To confirm the other part. 
if you set Washer to Empty or anything else the flow triggers but no confirmation is asked. Else is executed immediately.


2017-07-20 21:15.09 Variabele Washer is: iets 
2017-07-20 21:15.09 Test#1691 Else
2017-07-20 21:15.09 Countdown Washer gestart
2017-07-20 21:16.13 Countdown Washer leeg

2017-07-20 21:20.41 Variabele Washer is: Empty 
2017-07-20 21:20.41 Test#1691 Else
2017-07-20 21:20.41 Countdown Washer gestart
2017-07-20 21:21.44 Countdown Washer leeg

**Comment by swttt** [comment]
So it should be triggering the ask for confirmation at least one the first loop. But i expect it looping even multiple times (with 10 min in between)

So here the flow triggers on the var Washer being set as `Finished`
WHEN `Var washer changed` AND `Washer is Finished` AND `washer isn't Empty` AND `Ask confirmation` THEN `set washer to empty`

What here happens is, the flow triggers. The first card in the AND column is `TRUE` so it continues to the second one. The second one is `TRUE` as well. Then it should ask for confirmation and it depends on your answer if it triggers `THEN` or `ELSE`.

If you say `NO` it starts a countdown, i suspect that you have a flow that sets the variable washer to `Finished` when the countdown hits 0. So the flow starts again after 10 minutes. And does the exact same thing.

But if you answer yes 1 time, you will get in a loop.

If you say `YES` it's sets the washer variabele to `Empty` and triggers the flow again. Since the first card checks if `Washer is Finished` it gives back `FALSE`. At that moment it isn't going to ask you the confirmation and goes to the `ELSE` directly. If my assumption is correct and the countdown triggers a flow that sets the variable Washer to Finished, this all starts over again.

**Comment by JerryVdV** [comment]
Thanks Dijker and swtt, really appreciate it. You are right, the flow is indeed not doing what it should (looping).
To avoid further confusion I replaced the screenshot and adjusted the text in the issue post on top.

So the issue of homey not listening remains after arriving at the confirmation question; the question is asked but Homey does not start listening (no ring lightning that indicates Homey is listening, i.e. the microphone is not on to receive speech input).

**Comment by Dijker** [comment]
I tried your new flow,  and set the ring to Spectrum. 
But I Can't reproduce your issue here (Also on 1.3.2 but only on Dutch )
both when I test using the Test button as with triggering by changing a Variable Homey stops Spectrum and turns pulsing Orange for a couple of seconds.  
If it hears something  it turns to spinning White.

Only when I disable the Mic it doesn't react as you say.
![image](https://user-images.githubusercontent.com/12412734/28438463-70ea410a-6d9e-11e7-934d-dd376a44ae50.png)


Bu guess you checked that?

**Comment by swttt** [comment]
And to add, does homey trigger on `Okay Homey` ?

**Comment by JerryVdV** [comment]
@Dijker Yes I did check that. 
@swttt sometime (usually after a reboot it works for a while), right now it's not. So it probably linked to the other issue #1612

**Comment by Dijker** [comment]
ok, so maybe it is just a duplicate.... 

if OK Homey works did you check the Confirmation trigger at that moment?
Do both behaviors appear at the same time ?
 
And does the confirmation also fix with a Reboot?

Maybe good to mention that with a log when it happens in the original Issue #1612 
Keep all knowledge about (probably) the same issue consolidated for the developer. 

Strange thing is that in your last screenshot your Conformation card has a red cross, this indicates Homey got (interpreted) a negative answer. Don't know if you said something to Homey after triggering?

**Comment by JerryVdV** [comment]
Just tested it after a PTP; Homey is listening (for the time being) as well as the confirmation flow.
I'll close this one and add the comments to #1612.
