### ISSUE TITLE
App crash Ledring disabled homey speech

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1692]
**What is your Homey version (Settings → System)?**
1.3.2

**What did you try to achieve?**
Go to bed flow

*Please include detailed steps how we can reproduce the issue*
App ledring crashed

**What was the result?**
Homey speech disabled
...

**What did you expect as result?**
Nothing happening with speech responsiveness

**Any other remarks**
Had to reboot homey but speech still not responding

**Please attach a Homey System log (Settings -> System -> Send Log)**
4D8D2E83F7
...

**Comment by swttt** [comment]
Just to be clear, because i can't make anything out of the issue:
1. you run a flow
2. in that flow you change the led ring (some led ring app?) and disable speech?
3. led ring app(?) crashes and speech isn't disabled?

**Comment by satbopper** [comment]
no what he means i think is simple and i can confirm this because it happened me also that after a crash of an app,hue ledring or what app else,homey does not respond anymore to ok homey
everyday apps are crashing here (sigkill) for no reason,memory is ok

**Comment by swttt** [comment]
Doesnt change the fact that its still a loop if you ask me 😮

**Comment by bvdbos** [comment]
No, the microphone-process has a low priority and is killed as one of the first internally I think...

**Comment by swttt** [comment]
Removed my last comment, wasn't meant for this issue :D

**Comment by satbopper** [comment]
i am convinced that the crashing of apps has to do with badly programmed apps which freaks up the memory,the remarkable thing is here that only large apps like hue,sonos,ledring will crash.
for quite some time now i am testing every app for two days and watched the memory and crashing apps
now i am at the harmony hub app,i only disabled it,including the possible flows,for almost one day the memory,swapp file is stable-system 170 mb swapp 186 mb,no crashing apps,looks promising
allthough it is a pitty if it is the harmony app that no one has the ability to pick up the problems with the app,because if have a dreambox 8000 sat receiver that you can control perfectly with the harmony app
my total amount of apps is 25,lets wait for another couple of days

**Comment by swttt** [comment]
@satbopper Indeed it could be apps that are leaking memory indeed. But i have seen flows being capable of this as well.

**Comment by jeroenvollenbrock** [comment]
Your log shows out of memory issues while trying to load over 30 apps. Does the problem still occur when you run less then 15 apps?

**Comment by chrisboer** [comment]
Never tried but did not have these issues before 1.3.2

**Comment by bvdbos** [comment]
dupe of #1612 ?

**Comment by chrisboer** [comment]
Issue resolved with 1.5.2 rc6 did not uninstalled any application have 28 Apps currently installed
