### ISSUE TITLE
Niet verbonden met Athom Cloud. Homey offline

### ISSUE THREAD

**Issue by hterd** [athombv/homey#1775]
**What is your Homey version (Settings → System)?**

1.5.0.-rc2

**What did you try to achieve?**
Homey connect to Athom Cloud
Restart several times. Doesn't solve the problem.

*Please include detailed steps how we can reproduce the issue
?? No connection to Athom Cloud. Homey is oflline
Some things work ok. Some flows don't work???

**What was the result?**
Homey offline.  

**What did you expect as result?**
A Homey that works correct!!!!!!!!
Before 1.5.0-rc2 everything was Ok.
I was on hollyday (2 weeks) and could not make contact to Homey.  Homey is Offline
(So two weeks not able to see whats going on in my house.) Thanks a lot.
Now I'am at home and can see the flows etc. But get a message "Niet verbonden met Athom Cloud" ???

**Any other remarks**
How can I connect Homey to Athom Cloud. ?

**Please attach a Homey System log (Settings -> System -> Send Log)**
Cannot send a log. When I click "Send log" I get an Error "Homey is Offline"

**Comment by Dijker** [comment]
Fixed in RC6 probably....
https://firmware.athom.com/

Personal note: 
don't update just before your holyday to the latest experimental....  
(dont update anything that two weeks, e-readers briked, Phones and Navigation wiped. all had it before ;-) ) 
my freeze was before august to stay on 1.3.2 for the holiday. and I bought special for the Homeys a TP-Link  to PTP (WiFi-Cloud conected)  for the Development Homey that indeed disconnected as I was updating that one during my Holiday.

 https://apps.athom.com/app/nu.baretta.tplink  
just my 2 ct.

**Comment by hterd** [comment]
Fixed the problem.
A few weeks ago I activated VPN on my Netgear Nighthawk XS4 router.
I deactived the VPN on the router and afther rebooting everything Homey was working Ok again and also was connected to the Cloud again.
Installed Homey 1.5.0-rc.8 and al flows and apps are working ok.

So the activation of VPN function on the router was causing the problem.
