### ISSUE TITLE
Fibaro Motion Sensor suddenly not connected anymore

### ISSUE THREAD

**Issue by roelhendr** [athombv/homey#1818]
**What is your Homey version (Settings → System)?**

1.5.2

**What did you try to achieve?**

My Fibaro Motion Sensor did not report anything anymore. When looking at the zwave network graph it was not 'connected' to Homey anymore. Never had problems with this. The sensor is about 2 meters away from Homey.. Restarted Homey and still the same

**What was the result?**

No communication with the sensor anymore

**What did you expect as result?**

A nicely working sensor which communicates with Homey

**Any other remarks**

**Please attach a Homey System log (Settings -> System -> Send Log)**
It's about node 18 in the logs:
[zwave logs.txt](https://github.com/athombv/homey/files/1305942/zwave.logs.txt)

Homey log file code: D55285419F

**Comment by ivleth** [comment]
and waking up the device, does that work? I had the same issue with not responding fibaro motion sensors as well. What I did before even removing and re-adding it was changing a setting of the sensor, hit save. (dialog: settings will be updated on next wakeup).
Then I woke up the device and updating the settings to the correct value (dialog: settings saved). If this is not the case then I am afraid you need to re-add them. Besides that,  have tons of zwave issues since 1.5.x as well :-(

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please open a new issue if you still encounter this issue with the [latest Homey version](https://firmware.athom.com/).

Thank you!
