### ISSUE TITLE
Wait until something is done in a flow before doing next

### ISSUE THREAD

**Issue by warting** [athombv/homey#1834]
I would like an option to wait for a task to be done before doing the next task in a flow. When arriving home I would like to turn on/off a lot of devices (30+) but there seems to be some trouble when adjusting lots of zigbee devices at once and some of them are beeing skipped. I have partly solved it with delays but that is not good enough.

**Comment by RobinBol** [comment]
Hi @warting, thanks for reporting your issue. The actions in Homey's Flow are executed parallel, this is not something that will change. Besides, that would be a work around to the real problem: addressing multiple zigbee devices at once. This will be fixed in the near future though, for now lets continue the discussion in this issue (https://github.com/athombv/homey/issues/1859) to keep our issue tracker clean and without duplicates.
