### ISSUE TITLE
 Thermostat temperature

### ISSUE THREAD

**Issue by Korenets** [athombv/homey#1836]
Homey Firmware Version: 1.5.2 

It is not possible to set the thermostat temperature above 28 degrees.
The description of the operation of thermostats indicates up to 50 degrees

https://drive.google.com/open?id=0B1vxUzU0x8vIMWxiZ01ocHRDbk0    -   Photo!

An example from the manual Stella Z:

Comfort: The temperature in the room will be regulated to a comfortable level. On factory default this is 22 °C but the value
can be adjusted by the respective Z-Wave command 'Thermostat Setpoint' to a value between 0 °C and 50 °C. This mode is
active on factory default.

And in the app eurotronic Stella Z:
Characteristic.TargetTemperature = function() {
  Characteristic.call(this, 'Target Temperature', '00000035-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    unit: Characteristic.Units.CELSIUS,
    maxValue: 38,
    minValue: 10,
    minStep: 0.1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

Thank you

**Comment by caseda** [comment]
Maybe start with what device/app you had trouble, needed to read everything that it is in my app :wink:

Not sure why you want anything higher then 28 degrees, but I will change it in the rewrite to sdk2

And also keep 2 entirely different issues *separate*, if causes a lot of confusion, can't even assign developers now since both issues are totally different developers

So please close this one and create them separately. 
app issues on the [app github](https://github.com/caseda/org.eurotronic/issues) page
And standard homey issues here.

**Comment by caseda** [comment]
Though you also need read the manual better next time :smile: (so did i need to do it as i put in 38 as max temperature)

the 0 - 50 is the `operating range` (the range it will keep working), the `Control range` is only from 6 to 28 degrees celcius
