### ISSUE TITLE
Zone name in device name (improvement)

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey#2020]
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

When you have a device which includes the zone name, zone switching becomes a problem. 

**What was the result?**

For example "Turn on lights in living room" gives a "No lights found" error when you have a device name with the name living room (in it). 

**What did you expect as result?**

**Any other remarks**

This behavior is annoying and wrong because I want to give sensors a logical name (like PIR living room, Climate Living Room) so I can find them easily in the flow editor. 

There should be a check that excludes non-light devices from this behavior.

**Comment by Tweake** [comment]
What you are describing has been an intentional design decision. Adding the name of a zone to a device in that zone is redundant and will make speech requests unnecessarily more complex. 

Zone names are also already displayed in the Flow editor, so it does not add value there either.
![screen shot 2018-01-02 at 11 34 45](https://user-images.githubusercontent.com/10051731/34481215-21571dc6-efb1-11e7-841a-740f062d36e0.png)

**Comment by DieterKoblenz** [comment]
It's a flaw when you want to turn on lights in a zone and it won't work because a "**not light device**" has the same name as a zone. From a technical standpoint, you shouldn't try to turn on devices which aren't lights.

(And it doesn't make speech requests anymore complex, but that's besides the point)
