### ISSUE TITLE
Homey Software Version 0.0.0

### ISSUE THREAD

**Issue by djeskoswe** [athombv/homey#209]
Hi 

Version shows 0.0.0  , did recovery and then a update.

![version](https://cloud.githubusercontent.com/assets/17300121/13120152/b4da7802-d5ac-11e5-9933-31458dbe096e.JPG)

**Comment by jeroenvollenbrock** [comment]
Hi there!
In order to help you i'll need some more information:
- what kind of recovery did you do? full recovery over USB, or the regular recovery?
- are you on the beta channel or stable channel?
- what version did you update to (eg: what version was supposed to show there?)
- did you update through the setup.athom.com wizard, or through homey itself?
- did you use automatic updates or did you install the update manually?
- did you interrupt the update, unplug homey during the update, or interfere with the update process in any kind of way?
- if you disable automatic updates, does homey then show a full update to version 0.8.17?

**Comment by djeskoswe** [comment]
Hi 

First:
I got the unit from a GEEK backar that did a recovery from the guide ( Mac USB recovery)

Then i did a hold upside done recovery and clean all settings ,  setup all good but no version number. 

When i disable auto update it says update 0.8.17 is ready to download , did not that yesterday 

Safe to run it ?  

thanks

Niklas

**Comment by jeroenvollenbrock** [comment]
@djeskoswe:
Yes, it is safe to run it, but it is very important that you do not interrupt the update process. The 0.8.17 update that is standing by will take longer than usual, because it contains the entire image, and not just the latest changes.  If you interrupt the update process, a new USB recovery is needed.

**Comment by djeskoswe** [comment]
thanks , you can close this case

**Comment by jeroenvollenbrock** [comment]
Alright. If the problems persist, please send an email to our regular support team at support@athom.com
