### ISSUE TITLE
[Developer tools] [Bug] Z-wave network diagram not representing actual state

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#2148]
**Metadata**

* **Homey Version**: 1.5.6-rc8

**What did you expect as result?**
To have the diagram the same representation as the Nodes list and their routes

**What was the result?**

As you see in the below screenshots, node 6 has a route via node 51.
However this is not visible in the diagram.

Another example: node 51 (which is mains powered and thus an Z-wave router) isn't connected to ID 1 (Homey).
This is however correctly shown in the nodes list.

![diagram1](https://user-images.githubusercontent.com/15921016/34767797-512b1e50-f5f9-11e7-9994-83b922c8b0fb.png)
![diagram2](https://user-images.githubusercontent.com/15921016/34767799-51409db6-f5f9-11e7-9dc0-ac720ff96098.png)
![diagram3](https://user-images.githubusercontent.com/15921016/34767800-51557a9c-f5f9-11e7-8000-0651d737de3e.png)

**Comment by razorfish79** [comment]
Same here.

Just one example and I have loads of it.

![image](https://user-images.githubusercontent.com/3584214/34774902-8497d518-f611-11e7-91dc-aac4cf210628.png)

Did not have any Z-wave issues before 1.5.6 RCx
Also some are marked as offline but they work. 

Log Code: 1031163567

**Comment by WeeJeWel** [comment]
We're going to remove the diagram altogether - it doesn't add any value anymore.

**Comment by cbho** [comment]
That's a shame - it looks really cool...
Keep it as a way to visualise stuff - just with a note that it might not always be completely exact :-)

**Comment by razorfish79** [comment]
I also found it very helpful (if it would be correct).

Removing it would remind me in some case like Apple did with removing remaining battery life. 

"Removing because we are not able to make it work"

**Comment by Inversion-NL** [comment]
I agree. Especially the mouse over to check the connections which an specific device has.
Would be a shame...

**Comment by Veldkornet** [comment]
I miss the diagram already :(

**Comment by Fire69** [comment]
Whut?  Sorry, but this is just stupid...
Just sent in the survey, if I would have seen this earlier I would have given a lower score for this firmware.

**Comment by canedje** [comment]
huh?
Removing because there is something not working properly?
Thats not a good solution IMO

**Comment by WeeJeWel** [comment]
It's not that it had bugs, but the visualisation simply didn't made sense. The table gives all information that's available.

**Comment by Veldkornet** [comment]
If it wasn’t broken, was it causing any issues? Page space that you need for something else?
The table shoul (when it has any information in it) provide a lot of useful information, but the graph for me has a completely different purpose. 
Unless you plan to put that graph in the new Android / iOS app, as I’m guessing the table has too much info on it to show it in the app. 

Personally, I found it quicker and easier to see which devices are connected to which compared to that chewed up spiderweb in the settings. 

The table you would need to scroll through the table to see what the numbers represent, although it does of course provide other useful information. Also, my table is pretty much empty since I’m still on 1.5.3. 

So I guess I’ll just have to use that chewed up spiderweb in the settings menu.

**Comment by Veldkornet** [comment]
The only “buggy” related thing I found, from a 1.5.3 point of view, for both the table and graph was that if a new device was added to the network, it didn’t show on the table / graph until Homey had a reboot.

**Comment by bvdbos** [comment]
Afik, see above in the OP, the graph was showing all kind of connections which didn't exist. Think Athom used http://visjs.org/network_examples.html at first but that caused issues with larger networks. Maybe you can find a working library?
