### ISSUE TITLE
[SUGGEST] Exit strategy for Experimental Users

### ISSUE THREAD

**Issue by konradwalsh** [athombv/homey#2208]
Can I recommend that Athom provide an exit strategy for Experimental Users?
Periodically, you will merge all stable and experimental versions at a key milestone. Then alert the user that they have the option to revert to the stable channel if they wish when choosing which update to apply.

Some users end up on experimental regretfully or because its the only way forward whilst await some X feature to be released. But it might not be a good place to be once the feature moves to the stable channel.

**Comment by jeroenvollenbrock** [comment]
There is an exit strategy, it is described here: https://www.athom.com/support/KB000041/ 

Unfortunately, keeping an option to revert to stable while mantaining your settings is impossible. This is due tot the fact that we need to be able to guarentee that a homey on the stable channel has settings that were all generated by software that has been in the stable channel as well. Otherwise, an experimental update has the potential to set or change settings that could later cause problems after a revert to the stable channel. It is however possible to disable the automatic updates and only install the software versions that got promoted to the stable channel.
