### ISSUE TITLE
Resetting meter values does not work for neo plugs

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#2216]
* **Homey Version**: 1.5.6-rc.11, also not working in previous rc's
* **Homey Log Code**:  A80F5246C3

**What did you try to achieve?**
I have 8 neo plugs and one fibaro plug. I have a flow that resets these meter values every month. All Neo plugs are not resetting the power meters. Only the Fibaro does his job.

**What did you expect as result?**
Reset power meter

**What was the result?**
No reset of power meter

**Any other remarks**
This issue also existed in 1.5.3

**Comment by jeroenvollenbrock** [comment]
This is probably an issue that is not related to homey but the implementing app, in this case the neo app. Maybe @mruiter can be of assistance?

**Comment by mruiter** [comment]
Support of the reset meter devices has been pulled out of the z-wave mesh driver because of it non working all the time and lack of time to implement it further in the Mesh driver.

This is no problem at all, i just moved the reset meter commands back into the Neo app driver.
The App is peding approval . So i guess it will show up in the appstore soon.

Guess this issue can be closed. If new issues surface please make a issue in the Neo Homey App github repro

**Comment by jeroenvollenbrock** [comment]
Solved in NEO Coolcam v2.0.6

**Comment by Fiek1** [comment]
@mruiter thnx everything working again

**Comment by mruiter** [comment]
Youre welcome
