### ISSUE TITLE
Flow stop working

### ISSUE THREAD

**Issue by mbjornbe** [athombv/homey#2320]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

I have a Fibaro motion sensor in my living room. I have created a flow to tigger on motion detection and start a light at 20% in my living room through Philips HUE. If i test it its working as a flow, but when I trie to tigger it "alive" it does not work.

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker
