### ISSUE TITLE
[com.plugwise] Does not find my Stretch 3 on Wifi nor on LAN

### ISSUE THREAD

**Issue by andrede** [athombv/homey#2365]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment]
Could you be more precise, fill in the requested fields etc? When did you buy your Stretch, which firmware is your Stretch on etc?

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker.
