### ISSUE TITLE
URGENT: Wifi not always working

### ISSUE THREAD

**Issue by Rido** [athombv/homey#2424]
* **Homey Version**: 1.5.9
* **Homey Log Code**: C80683DF4F

**What did you try to achieve?**
Try to get Homey online after a "freeze".

**What did you expect as result?**
After a reboot Homey would appear online on my network and be able to control my home.

**What was the result?**
Homey stays offline. The wifi interface isn't working.

**Any other remarks**
First I rebooted Homey multiple times. This didn't work.
Then I tried to put Homey in recovery mode but then I couldn't find any wifi networks. Filling in the SSID + password didn't work as well.

Then I _(don't laugh)_ shaked the Homey and tried a new reboot and this time Homey finally connects to my Wifi network. 
But this occurs almost each week.. 😢

**Comment by bvdbos** [comment]
Did you look at your router to see if Homey is online? How long did you wait before testing, Homey takes some minutes to boot. I didn't see any other reports about failing wifi, how strong is your connection? Did you try to access Homey on its internal IP-address?

**Comment by Dijker** [comment]
Hi Rick, 
beside the valid questions from bvdbos, 
when answered maybe the community is already able to help you find the root cause of your problem.

Also Please look at https://github.com/athombv/homey/blob/master/CONTRIBUTING.md

My Advise: 
It is up to Athom to assign Priorities, Home Automation and Homey should be FUN and if you feel it is URGENT I would advise to change your automation to be not dependent on Homey.
(I think it will make it more fun and less stressful)

Whenever you think of doing things that are not in manuals en you expect to make others Laugh: 
- Calm Down 
- Put Homey unplugged in the corner and take a break
- Re-plug Homey and Put her in the corner to take another break.
- Write an Email to Support @ Athom.com if you stil have a problem and feel it is urgent for you, that works better for regular support. Check Homey just before you press Send if she didn't fix magically. 

I didn't see Wifi connection problems recently on GitHub, Support can tell you if there are other know Issues not already registered at GitHub, They can maybe also see in your logs if something happens on your network. 

Final question: 
What did you just before Homey going offline? or was is spontaneously?

**Comment by Rido** [comment]
@bvdbos Yes, I did. I checked the router several times and Homey didn't appear online on the network. I also tried to ping Homey, but this failed. I waited more than 15 minutes before checking.
My wifi connection is great. I use several Unifi AP Pros indoors and Homey is near an AP.

@Dijker I apologize, but are you now advising not to use Homey if I am dependent on my home automation?

But it's spontaneously and random. 
A friend of mine already created a flow to reboot Homey each 4 hours to prevent a freeze/crash 😂

**Comment by bvdbos** [comment]
A reboot every four hours looks like some flows which are causing a loop. My Homey can be online for over a week without a reboot needed. As for @Dijker : I think he reacted to the "urgent" part mostly, you shouldn't get frustated working with Homey :) For urgent things you better send a mail to support@athom.com.
