### ISSUE TITLE
[com.somfy] blinds not working after upgrade to 3.0.1

### ISSUE THREAD

**Issue by nhassink** [athombv/homey#2441]
* **Homey Version**: 1.5.9
* **Homey Log Code**: 5ED8081014
* **Smartphone Platform**: iOS
* **Smartphone App Version**: v2

**If related to a Homey App:**
* **Homey App Version**: 3.0.1
* **Homey App Log Code**: 62a7382e-5059-4a35-8121-9a72a1b14800
* **Affected Devices (preferably product codes)**: RTS sunscreen

**What did you try to achieve?**
Operate my sunscreen

**What did you expect as result?**
Moving sunscreen

**What was the result?**
Nothing. All sunscreens appear as non-available after the update to 3.0.1

**Any other remarks**
I did not change anything. The update seems to have broken something.

**Comment by jeroenbos22** [comment]
Same here

**Comment by SailingDuck** [comment]
Worked fine for me on 3.0.1. Old/new app on Android where ok.

**Comment by BasKiers** [comment]
Hi, 

I've just reverted the somfy app to v2.1.12 (which now has version number 3.0.2 in the app store) as a quick fix for affected users. I have determined the cause to be that in v3.0.1 I removed the old (deprecated) drivers which the app was using from december 2015 untill november 2016. For all versions v2.x the app still contained the old drivers of v1 but only ran them in shadow mode for the users that had already paired their somfy blinds. 

Unfortunately, since the current version is build for a newer SDK version (v2) it is impossible to run the drivers in shadow mode and support the old drivers. I will look into the possibility of re-pairing your somfy blinds with the same signal for which you will not have to put your blinds in pairing mode. If this is not possible you will need to re-pair your blinds by programming a new signal from homey into your blinds.

Regards,
Bas

**Comment by Orkymannen** [comment]
Hello Bas,
Does this mean that it should work with 3.0.2 if I just re-pair my sunshade again? I could live with that, because now it does not work at all, even with 3.0.2. It worked great before this.

**Comment by BasKiers** [comment]
Hi,

Hmm your blinds should work with v3.0.2 or you might have a different issue than the one I am referring to. Could you try to re-pair your sunshade? 

Regards,
Bas

**Comment by Orkymannen** [comment]
Thanks for the quick reply. It worked again after a re-pair.

Best regards,
Patric

**Comment by nhassink** [comment]
Thanks for the quick fix. Worked for me.

**Comment by nhassink** [comment]
And 3.0.4 broke things again. Sunscreens do not stay unavailable anymore but they do not react to commands from homey. Shall I send another application log? Or Do I need to re-pair ?
