### ISSUE TITLE
[nl.klikaanklikuit] APC3-2300R support

### ISSUE THREAD

**Issue by menjuice** [athombv/homey#2453]
Can't get it to connect to homey with the app

**Comment by Dijker** [comment]
Hi!
Did you read the Contributing guidelines?
https://github.com/athombv/homey/blob/master/CONTRIBUTING.md

This issue tracker is for bugs and issues found within Homey and Athom Apps.
If you require more general support contact Athom's support team
at: support@athom.com

Request for support of new devices can be done in a new Form: https://go.athom.com/request-device-support

Please Fill in the requested information if You think it is a bug, it already was in the template: 

**Metadata**
* **Homey Version**:
* **Homey Log Code**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:


and By The Way: 
KAKU uses one standard signaling and almost all their 433 devices function the same.
as reported by an other user here #2380 (comment) you can use them as one of the other devices, like the APA2-2300R

(if it works, please report back and close this issue yourself ;-) )

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md)? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
