### ISSUE TITLE
[nl.klikaanklikuit] ASUN650 up signal issue

### ISSUE THREAD

**Issue by stephannnnn** [athombv/homey#2467]
Homey firmware 1.5.9
Klikaanklikuit versie: V3.1.5

Since a couple of days my ASUN 650 is not responding well on the up signal. When I give the down signal the screen goes all the way down. When I give a up signal the screen goes 5cm up and stops. When I control the screen with a paired remote it goes up in one movement.

The problem must be in the app. Before (couple of months ago) it worked fine.

**Comment by bvdbos** [comment]
Very unlikely as the app didn't change (3.1.5 was released 11 months ago). Did you update your firmware recently, like in the past couple of days? Or do you have any flows which may cause this? Could you provide the log like asked in the template?

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker
