### ISSUE TITLE
[com.fibaro] Describe your issue here

### ISSUE THREAD

**Issue by remcovaal** [athombv/homey#2484]
**Metadata**
Fibaro is using all kind of model numbers, why are they not visible in the GUI. Such will selecting the correct component much easier.

Z-wave is unreliable, so it will be helpful if there is some additional diagnostic to see what went wrong.
* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by caseda** [comment]
The right driver will be selected automatically, even if you select the wrong one, product type numbers are sometimes wrongly given on websites/webshops, or almost the same (fgr222 vs fgrm222) even on the packaging, so to stop confusion it is not displayed during inclusion just the official full names

Diagnostics like those in the [developer tools ](https://developer.athom.com/tools/zwave)?

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker
