### ISSUE TITLE
[com.qubino] Describe your issue here

### ISSUE THREAD

**Issue by 1PGalich** [athombv/homey#2488]
Привет!
Пожалуйста, добавьте поддержку Qubino Flush On/Off thermostat zmnhid1  !

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker
