### ISSUE TITLE
[com.devolo] cannot add devolo key fob

### ISSUE THREAD

**Issue by MartinMotz** [athombv/homey#2522]
I bought myself a Devolo key fob to arm/disarm the alarm.
At first I succeeded to add the device on the first attempt.
After less then 30 mins the battery seemed to be empty.
Whatever I tried, none of the buttons seemed to work.
so after replacing I still received no response from the device so I decided 
to remove the device from Homey. Later I found that I could reset the device to it's factory default
settings and found all buttons responding. Sad enough I cannot add the device to Homey anymore.
So I tried to remove Z-wave device but there was no device to delete.
I don not have a clue how to add the device though it seems to work now (but not in Homey)

Any suggestions?
Thanks in advance

**Metadata**

* **Homey Version 1.5.11:

**Comment by RobinBol** [comment]
Hi! Thanks for reporting your issue. What I can make up from your description is that the Keyfob does not send the 'inclusion' information to Homey, without that the device can not be added to Homey. Maybe the device is in some sort of locked mode (where in-/exclusion is not possible) or the battery issue remains. Anyway, this problem seems to lie with the Keyfob itself, and not Homey. Since we are not experts in every device that can connect with Homey I think it is best if you contact Devolo support, they are likely better equipped to help you with your problem.
