### ISSUE TITLE
[Enhancement] having an IR-gui would be helpfull

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#264]
**What is your Homey version (Settings → System)?**
0.8.20

**What did you try to achieve?**
use Homey as an IR-device

*Please include detailed steps how we can reproduce the issue*
Create/Learn an IR-device and try to control audio-set. 

**What was the result?**
It's only possible with flows, you can't send signals through the "devices and zones" panel. 

**What did you expect as result?**
Would be helpfull to send signals through the web-interface.

**Any other remarks**
The same holds for the android-app, my IR-device doesn't show up in my zone...

**Comment by Qx5** [comment]
+1
Also useful for testing newly added devices.

**Comment by goldenice** [comment]
If I understand correctly, you'd like to have a card with some buttons on them. The reason this currently isn't implemented is that we can hardly put every button of a remote on a card, because remotes may have well over 30 buttons. 

Say we would add cards for IR-devices: 
- Would you need them for every device, or only for a few of your remotes (for example: the audio system should have a card, but the tv should not)
- What is the absolute minimum amount of buttons you need for the card to be useful? (Power? Volume control? Channel up/down?)
- What devices would you be interested in controlling? Only the audio system, or tv's as well? How about beamers?

I hope you guys understand it's pretty hard to create a generic card for every IR-device; a beamer is a totally different device from an audio system, and that makes it difficult to reflect this in one card for every IR-device. We are planning on improving the IR-system, some answers to the questions above would make that a lot easier.

**Comment by RemonBerends** [comment]
@Goldenice if i take 10 remote controls from av devices together i see a lot of common buttons on them all.

- Power
- Source
- Nummeric 0-9
- Volume up / down
- Program up / down
then maybe add yet FFD/BWD/Play and Pause and i think for now you have already covered a lot of functionality.

Then this would be a template with 20 buttons.

**Comment by goldenice** [comment]
@RemonBerends I know there is a lot overlap between remotes, but I can't really put 20 buttons on one tiny card, and I don't think we should: Homey is meant to be a hub for all your smart device, not the ultimate universal remote control. Even if we would implement cards, I think it might be much more interesting to do this per device class, and not per generic IR-device. I'd much rather see a TV-card with a channel switcher only, and a separate audio set card with volume control than the two of those combined in one generic IR card.

I understand the request for more control over your devices using cards, but I believe we should take another approach than simply slapping some buttons on a card, because the only thing that would be is a remote control on your android device, and I believe we can do better than simply digitizing remote controls.

**Comment by goldenice** [comment]
In the future we wish to add deviceclasses to added remotes, but we're still deciding on the implementation (although we have some pretty good ideas about it). I'm closing this issue for now, but if anyone has any interesting views on this problem, please feel free to comment (and reopen).
