### ISSUE TITLE
[Feature request] Google Home - let it work with Dutch speaking Homey and Home

### ISSUE THREAD

**Issue by Keverjeroen** [athombv/homey#2692]
**What did you try to achieve?**
I try to use Homey with the Dutch-speaking Google Home Mini speaker. When I speak Dutch of English, Homey won't work.

**What did you expect as result?**
I could give commands via Google Home to Homey, even when I give the commands in Dutch and when Homey is set to Dutch.

**What was the result?**
When I talk Dutch (Ok Google, praat met Homey), it doesn't understand me.
When I talk Englisch (OK Google, talk to Homey), it says that I have to change the language of Homey to Englisch.

**Any other remarks**
Speaking Dutch to the Google Home speaker is in Beta, but in the developper tools from Google, you can already use the Dutch language. So if you can create a Google Action in Dutch right now, you are one of the first domotica-companies when Dutch goes live for everyone!

**Comment by Keverjeroen** [comment]
Since of today, the Google Assistant can speak Dutch. Check: https://assistant.google.com/explore?hl=nl_nl

**Comment by jjtbsomhorst** [comment]
But can Google talk to Homey in dutch?

**Comment by WeeJeWel** [comment]
Yes, we are working on this.

**Comment by rogierhofboer** [comment]
Want to add that the Dutch integration 'works', but adds the start of implicit invocation text ("vraag homey") to the homey speech-input. This gives problems with certain setups (combination of apps / device & zone names).  It doesn't do so for the English version and IMHO should not add it.

"Ok Google, vraag homey om de gordijnen dicht te doen" 

current speech-input -> "vraag homey om de gordijnen dicht te doen"
homey responds with -> "ik heb geen gordijnen kunnen vinden"

expected speech-input -> "om de gordijnen dicht te doen"
homey response with -> "ik zal de gordijnen dicht doen"

This might be an issue in Google Actions SDK and not Athom's fault.


Explicit invocation also doesn't work, probably because of the same issue:
 
"Ok Google, praat met Homey"

results in speech-input -> "praat met Homey"
homey response -> "Het spijt me, maar ik begrijp niet wat je bedoelt"
homey ends conversation.

@WeeJeWel should I create (a) separate issue(s) for this?

**Comment by SailingDuck** [comment]
Can see this too in /manager/speech-input/
![](https://i.gyazo.com/d25d5274385dd33bb2b1c7e3636f8baf.png)

**Comment by WeeJeWel** [comment]
Fixed!
