### ISSUE TITLE
[nl.klikaanklikuit] Device support for ACM-3500

### ISSUE THREAD

**Issue by corkorten** [athombv/homey#2718]
i had programmed them and used them worked perfect after update i must program then this tim as a acm 2300 h a lot of work 

can you make a driver for the acm 3500 then i can program them next time and is this no issue more

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
Hi, 

Could you please take another look at Athom's [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and fill in all missing information or close this issue?

The more information Athom has, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact Athom through support@athom.com instead of using the bug tracker

What device ID have you used  before that doesn't work anymore? 

Can you send an Homey Log and an Application Log to the Developer 
and mention the Log codes in your issue? 

An App Log is send pressing the Alt-key after klikking behind the Application name

![image](https://user-images.githubusercontent.com/12412734/43486239-93171e36-9513-11e8-84f3-a5ca87f177dd.png)

The generic Log using the Send Log to Athom from the Settings System.

**Comment by KyleAthom** [comment]
Duplicate from https://github.com/athombv/homey/issues/2071.
Development for this device is currently ongoing.

**Comment by KyleAthom** [comment]
The device is available in the current KlikAanKlikUit app (version 4.0.10)
