### ISSUE TITLE
[nl.klikaanklikuit] Doorbel keeps Ringing

### ISSUE THREAD

**Issue by Tim-Brass** [athombv/homey#2719]
I have a flow that is triggers when the doorbell is pushed. It keeps triggering continuesly after 1 push

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
Hi, 

Could you please take another look at Athom's [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and fill in all missing information or close this issue?

The more information Athom has, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact Athom through support@athom.com instead of using the bug tracker

What device ID have you used? 
Can you send an Homey Log and an Application Log to the Developer 
and mention the Log codes in your issue? 

An App Log is send pressing the Alt-key after klikking behind the Application name

![image](https://user-images.githubusercontent.com/12412734/43486239-93171e36-9513-11e8-84f3-a5ca87f177dd.png)

The generic Log using the Send Log to Athom from the Settings System.

**Comment by KyleAthom** [comment]
Issue moved to https://github.com/athombv/homey/issues/2725
