### ISSUE TITLE
[Enhancement] export/import IR devices

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#272]
Would be nice to be able to export and import a newly learned IR-device. Saves yourzelf (and others if we can exchange these exports) a lot of learning time (Also my tv-remote is broken so I can't learn Homey how to change the channel)

**Comment by goldenice** [comment]
Why exactly does this save a lot of trouble? The only use case I can imagine is having a family member or friend with the same type of TV using your configuration. However, the entire process of exporting, sending it to that person and importing it there seems rather cumbersome versus just re-pairing the remote over at the other persons' Homey.

It would probably not be that hard to build, but I'd like to see a use case specified first, because I don't think this feature would be used often enough to justify the cost of building and maintaining it. Then again, I could of course be wrong, so if you'd take the time to explain why this would be useful, I'd really appreciate it :wink:

**Comment by RemonBerends** [comment]
Well @goldenice i get the point of @bvdbos. If a remote is not recognized in the wizzard mode and u need to add all buttons manually, this is a lot of work if u need to do this for a few remotes. If this data could be stored in some database, and be used by all homey users, then this would save users with the same remote a lot of work.

Even if you needed to return sometime back to factory default and could import all this IR- learned devices again, it would be nice.

**Comment by bvdbos** [comment]
Those were exactly my ideas :+1:

**Comment by goldenice** [comment]
Right, I see what you mean. I'm not sure when I get around to it as my todo list is pretty long, but I'm going to think about a nice solution for this :)

**Comment by mvunen** [comment]
+1

**Comment by WeeJeWel** [comment]
We won't add this functionality, since some while ago there is an Infrared Apps SDK available, which does this and more.
