### ISSUE TITLE
none of my Telldus wall plugs works after the update

### ISSUE THREAD

**Issue by BusterKrabba** [athombv/homey#2721]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
Hi, 

Could you please take another look at Athom's [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and fill in all missing information or close this issue?
The more information Athom has, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact Athom through support@athom.com instead of using the bug tracker

fe, What Firmware is your Homey, 
What App name and version is the problem with? 
What device ID have you used?

**Comment by KyleAthom** [comment]
Issue moved to https://github.com/athombv/homey/issues/2724
