### ISSUE TITLE
ik krijg geen enkele fibaro module gekoppelt, 

### ISSUE THREAD

**Issue by Japio78** [athombv/homey#2727]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
Hi Japio78,
Could you please take another look at Athom's contributing guidelines and fill in all missing information or close this issue? This is an international community so please use English here on GitHub. 

The more information Athom has, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact Athom through support@athom.com instead of using the bug tracker.

Support can be e-mailed in Dutch also,
For help and support from the dutch community you can ask on the Athom Community Forum 
https://forum.athom.com/categories/nederlands

en nog even om te antwoorden op je opmerking:
Heb je het op deze manier geprobeerd? 
https://www.athom.com/nl/ondersteuning/KB000003/
en 
https://www.athom.com/nl/ondersteuning/KB000038/

**Comment by KyleAthom** [comment]
It seems hat you just need tot use the Fibaro app. As this is not a coding issue, this issue will be closed.  If you want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker.
