### ISSUE TITLE
[com.netatmo] Can't use Weather Station as "And" in flow

### ISSUE THREAD

**Issue by pbvbree** [athombv/homey#2735]
**Metadata**

* **Homey Version**: 1.0.4
* **Homey Log Code**: 
* **Smartphone Platform**: NA
* **Smartphone App Version**: NA

**If related to a Homey App:**
* **Homey App Version**: NA
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

At 13:00 ("When") I want to check the temperature of the Netatmo Weather Station, if the temperature ("And") is above 24 degrees Celcius then close the blinds.

**What did you expect as result?**

The Netatmo Weather Station should lock as "And".

**What was the result?**

It would not lock, so I can't use it.

**Any other remarks**
The blinds are are only on the west side, so this is only useful in the afternoon. Temperature change as "When" is very senseless I assume, as it would trigger often instead of only once. Or have I missed it completely? Thanks for your help!

**Comment by Dijker** [comment]
Hi PBVBREE, Welcome, 
Could you please take another look at Athom's contributing guidelines and fill in all missing information or close this issue? 1.04 is the version of your HomeyApp not Homey self that probably is 1.5.11 

This (GitHub) is an Issue tracker for Problems and feature requests. 

The more information Athom has, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact Athom through support@athom.com instead of using the bug tracker.

For help and support from the community you can ask on the Athom Community Forum
https://forum.athom.com/ or on Slack as a chat channel. Get your invite by entering your email address here and register for an Slack account. Login and join the conversation here: 
https://athomcommunity.slack.com 

and because we are a community and want to help you:
You find the Tag Temperature for your NetAtmo at the top and can use it with Logic in the AND column, 
 no need for a NetAtmo card in the AND column ;-)

![image](https://user-images.githubusercontent.com/12412734/43607670-28da3624-969f-11e8-8caf-bbeb881c7f44.png)

See you on the Forum or Slack!
Can you please close this Issue with the button down here as this is no issue of valid feature request.

**Comment by pbvbree** [comment]
Okay, there is probably something configuration issue on my side, Thanks for your reply!
