### ISSUE TITLE
[nl.klikaanklikuit] Alll switches are not working after update.

### ISSUE THREAD

**Issue by hanshoevenaars** [athombv/homey#2744]
After update all switches do not work. Can not see them anymore in Homey.
After restart they are visible again. But next day gone again. 
Not a good thing, try the update before running ?

[Kilk probleem.docx](https://github.com/athombv/homey/files/2265420/Kilk.probleem.docx)

**Comment by KyleAthom** [comment]
Hello Hans,

Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker.

Also, maybe you want to take a look at this issue if it's the same as the problems you're experiencing. https://github.com/athombv/homey/issues/2728

Thanks in advance!

**Comment by KyleAthom** [comment]
User contacted support, so ticket will be closed.
