### ISSUE TITLE
[nl.klikaanklikuit] Still invalid device data

### ISSUE THREAD

**Issue by johnotte** [athombv/homey#2766]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**
.11 weer invalid devices. In versie 10 zijn  de devices wel  bekend  maar wordt het zendsignaal niet herkend door de ontvangers. O.a apa3 -1500r

**Comment by KyleAthom** [comment]
Hello @johnotte ,

This is due a previously signal change made a long time ago.
If you re-pair the device with Homey on the newest version of the KaKu app, it should work fine again.
Since this issue is more a regular support issue then a code issue or bug I'm closing this issue. If you need further help you can always contact our support at support@athom.com
