### ISSUE TITLE
[nl.eneco.toon] Describe your issue here

### ISSUE THREAD

**Issue by herwarth** [athombv/homey#2770]
when Woonveilig sends a status change to toon, toon gets label no status in homey and not home, away or sleeping. toon itself shows the correct status.
using app 2.0.6 beta

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker
