### ISSUE TITLE
Remotec ZXT-120EU AC Extender

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2772]
* **Homey Version**: 1.5.12
* **Homey Log Code**: FCDA6563F5
* **Smartphone Platform**: NA
* **Smartphone App Version**: NA

**If related to a Homey App:** Remotec Technologies
* **Homey App Version**: v2.2.0
* **Homey App Log Code**: 
* **Affected Devices (preferably product codes)**: Remotec ZXT-120EU

**What did you try to achieve?**
Look at the device temperature 

**What did you expect as result?**
See the device settings like room temperature

**What was the result?**
Not showing details keeps giving the round circle /// waiting on details but not coming
![afbeelding](https://user-images.githubusercontent.com/23163409/44675450-db591280-aa30-11e8-8560-41023a0a1347.png)

**Any other remarks**

**Comment by danone1973** [comment]
It works fine for me.
I have included/excluded the ZXT-120 numerous times because some testing I was doing. Every time the small window was populated showing the correct temperature, controls etc.
I could control the air con from there, too.
The only time where I had dashes (-) on temperature was when I had wrong IR code entered. But even then there was no circle going round and round.

Can you control your air con from a flow card?

**Comment by jeroenvollenbrock** [comment]
This usually happens when the capabilities of the device no longer match the capabilities of the driver. You may need to re-pair the device. If that does not work, you can open the developer tools and look at the error. (I'm suspecting you'll see "Error: invalid_capability_id"). @tedtolboom might be able to help you in that case at https://github.com/TedTolboom/hk.com.remotec/issues

**Comment by TedTolboom** [comment]
@chrisboer indeed the Remotec app (and specifically the ZXT-120 driver) has been updated.
I try to avoid these disruptive changes as much as possible, but needed to do it for this update.

It includes some changes that might cause this behavior, hence the advice to re-include the ZXT-120 after the update. Which was announced in the changelog (in the app store and on the community forum): https://community.athom.com/t/remotec-technology-app-v-2-2-0/155/2?u=tedtolboom

The new ZXT-120 driver is fully tested and debugged by several users before the release. 
I don't expect further invasive changes to this device driver.
