### ISSUE TITLE
[com.jreenen.homeyharmonyhub] Harmony Hub app not recognizing activities

### ISSUE THREAD

**Issue by behgez** [athombv/homey#2801]
Is this app still supported, given there hasn't been an updated release in a year? No one is reacting to the issues reported.

The tag values for the devices do not change value when something is turned on/off. It stopped working about a month ago.

The only trigger that works is 'activity started'. I can't trigger anything that is related to 'activity stopped' or 'device turned off'. They are simply not recognized.

**Comment by jreenen** [comment]
Hi @behgez because of my busy schedule the last year, unfortunately, this project didn't get the attention it deserves. Next Thursday I will be having a 3,5 week holiday and I am planning to address all the open bugs. Keep an eye on the beta channel for updates. If for any reason I still can't make up to this promise I will try to find someone who can take over this project. Sorry for the poor support this last year.

Warm regards,

Jeroen van Reenen

**Comment by behgez** [comment]
@jreenen Big thumbs up 👍

**Comment by jeroenvollenbrock** [comment]
@behgez Could you re-open this issue at https://github.com/jreenen/com.jreenen.homeyharmonyhub/issues (The harmony hub app is not maintained by us)
