### ISSUE TITLE
[nl.klikaanklikuit] Describe your issue here

### ISSUE THREAD

**Issue by hakan-b** [athombv/homey#2818]
After version 4.0.10 and still 4.0.11 my switches do not work anymore via my Homey
The switches are 433mHz type EWT1004  from Telldus and was using the the AC1000 (if i remember correctly because I deleted and reinstalled without success

Any suggestion for a fix?
///Håkan

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
There are small differences between the KlikaanKlikuit devices and Telldus devices,
as these differences produced a lot of issues in the KAKU version 4.x app update Athom created a Telldus App specific for these devices.

Please install the Telldus App and pair your Telldus devices with this driver/App
https://apps.athom.com/app/se.telldus

Request support for a new Device please fill in this form: https://go.athom.com/request-device-support

Could you please take another look at our contributing guidelines?
https://github.com/athombv/homey/blob/master/CONTRIBUTING.md

The more information Athom has, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact Athom through support@athom.com instead of using the bug tracker.

For help and support from the community you can ask on the Athom Community Forum https://community.athom.com/ or on Slack as a chat channel. Get your invite by entering your email address here and register for an Slack account. Login and join the conversation here: https://athomcommunity.slack.com

**Comment by KyleAthom** [comment]
Hi @hakan-b ,

As @Dijker said, please use the dedicated Telldus app for those devices. There are made some changes to the KlikAanKlikUit app that are not compatible with other brands.
If you experience issues with the Telldus app, please create a issue for that app.
