### ISSUE TITLE
IR sends multiple signals instead of 1

### ISSUE THREAD

**Issue by kitkat14** [athombv/homey#282]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
Turn on the tv

*Please include detailed steps how we can reproduce the issue*
- Added the tv trough the wizard by pushing buttons till it get the correct tv 
- Created a flow to send Power button when i said Turn On TV

**What was the result?**
- When i try to test it, you can see that the led of the tv (to show that it received signal) blinks 3/4 times. Because of that sometimes my TV turns on and turns off (because its like someone pushing power button couple of times)
...

**What did you expect as result?**
That it will send only 1 time signal
...

**Any other remarks**

...

**Comment by goldenice** [comment]
This issue was already mentioned in #249 , however, I'm going to keep this open as this thread views it as a separate issue.

To the point: I'm working on a fix. Currently, the signals in the signal service (the serverside part of our IR recognition) are updated fully; those should be fixed mostly. The manually copied signals still have 10 repetitions as default. I put that down to 1, so that'll be fixed in the next Homey update.

Besides these fixes I'm currently working on adding an extra card in the flow editor, which allows you to explicitly specify the number of times a signal should be repeated. This could be useful for tv's that require you to keep the power button pressed for a few seconds before turning on.

**Comment by kitkat14** [comment]
That extra card solution (or config of the existing card) sounds perfect solution because then its tweakable for each device :+1:

**Comment by goldenice** [comment]
@kitkat14 Yep, that's what I thought. The code is done, and it's currently being merged and reviewed, so it'll be in the next update (0.8.21)

**Comment by kitkat14** [comment]
Nice will test it when it is released :+1: keep it up ;)

**Comment by JesperJanssen** [comment]
I now added my Sony remote automatically and when I now test a flow in the flow editor it indeed seems to just send one signal. However, to reach my HDMI 3 input I have to press the source button 3 times and when I configure a flow which presses the source button 3 times it will only go up from AV to HDMI 1 instead of AV > HDMI 1 > HDMI 2 > HDMI 3

For my surround set (logitech Z5500) it is not possible to use the automatic recognition.

But I will first wait until 0.8.21 is released and I did some testing with that version before I will report some more IR issues.
