### ISSUE TITLE
[com.qubino] ZMNHWD1 RGBW Dimmer Plus Support

### ISSUE THREAD

**Issue by ArchiSpec** [athombv/homey#2831]
Been requesting Qubinoe ZMNHWD1 RGBW Dimmer Plus Support for over a year ago now. I see my original issue no longer exists!

Any news please.

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
If you have any further questions regarding this issue, please contact support at support@athom.com, instead of using the issue tracker.
