### ISSUE TITLE
homey aint reacting to any speech anymore nor written speech with presence of flows

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#294]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
ask homey a simple question , like what is the time , what is the date. gives a thinking ledring but no result speech output. but it worked Sunday 28-02-2016 with 0.8.20

the only speech output is every three minutes:  Oops, I couldn't reach the server. Please try again later

1 checking speech input with http://myhomey/manager/speech-input/   (chrome developer mode)

2 sending with Postman

{ "transcript" : "what is the time" }

which worked until last Sunday 28-2-2016 with 0.8.20

gives this reaction
{
  "status": 500,
  "result": "undefined is not a function"
}

*Please include detailed steps how we can reproduce the issue*
 use speechinput page and see response 
see above

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by Arjanvde** [comment]
I'm sort of having the same issue since Sunday. Been giving Homey a lot of manual speech input on Saturday and Sunday and suddenly it stopped working. I tried to reboot the device 2 times and even had the power disconnected to relocate Homey but i couldn't get the input manager working again. 

As the topic starter i'm also on 0.8.20 and my system time is 1 hour off compared to the actual time.

Since i couldn't get the voice properly working i've switched the microphone off and didn't look at this anymore. Checking right now confirms this is still the case. 

In case a developer wants to view with teamviewer or have the credentials to log in please ask.

**Comment by nattlip** [comment]
deleting my flows made homey react on speech again

1 checking speech input with http://myhomey/manager/speech-input/ (chrome developer mode)

2 sending with Postman

{ "transcript" : "what is the time" }

which worked until last Sunday 28-2-2016 with 0.8.20

dont result in  this reaction
{
"status": 500,
"result": "undefined is not a function"
}

but in

{
  "status": 200,
  "result": {
    "transcript": "what is the time",
    "language": "en",
    "triggers": [
      {
        "id": "time",
        "position": 12,
        "text": "time"
      }
    ],
    "zones": [],
    "time": false,
    "devices": [],
    "agent": "homey:manager:cron"
  }
}

**Comment by nattlip** [comment]
still some bugs in flow though i think

**Comment by WeeJeWel** [comment]
If you got `undefined is not a function`, please send me a crash log just after it happens (Settings -> System)

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen if the problem persists.
