### ISSUE TITLE
Speech recognition sometimes completely stops working

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/homey#31]
Sometimes, all agents (things that react to speech) will never register. Homey will thus never respond to any speech command.

**Comment by WeeJeWel** [comment]
This can be checked by running in Google Chrome, while in the Homey interface, by opening the developer console:

`api('GET', '/manager/speech-input/agents')`

If the response (Network tab) is equal to: `{"status":200,"result":{}}`, then this bug is active.

**Comment by coldshivery** [comment]
Yep i also noticed sometimes homey just does not respond at all to "ok homey" multiple times after 30 seconds or so it responds again to my voice commands. I was unable to check in that time in the console.

**Comment by coldshivery** [comment]
This time i checked in the console it seems for me its always status 200 BUT it has results, even though it does not respond to "ok, homey" for a while.

**Comment by elgenioNL** [comment]
Same problem here.
1. OK Homey sometimes is not available for 30 seconds.
2. When the speech has been processed ( white ring stops) nothing is happening, doesn't start flows, turn on lights etc. 

During these periods i am able to force the transcript through the REST API: http://****/api/manager/speech-input/ 
and it works always 100%.

**Comment by mvunen** [comment]
Ok, can we resolve this by our self? Every command I say to Homey results in a dead silence...
I removed all my flows to test if that solves the problem, i worked once with the test command after that it keep silent again.

**Comment by JesperJanssen** [comment]
I'm also struggling to get homey to accepts my "Ok Homey" (it's almost impossible). However, when I clap my hand 2 times I get 5 checkmarks after 5 tries. After that I tried the flow which BasVanDenBosch was suggesting. Just let Homey repeat what you asked him.

So I clap my hand two times and ask him "what is the time" or "what will the weather be tomorrow" and he repeats not even one word I asked him but something completely different like "go to" or "what the".

I thought you were using the speech recognizing software from Google for the Homey. But the when I'm saying "Ok Homey" in the google translate app it actually writes down "okay homie". And Ok Google actually responds to my questions.

For now I will switch the voice control off because it's driving me crazy that he never responds to my ok Homey but responds to sounds in my house or on the television randomly.

**Comment by coldshivery** [comment]
For me when its not responding i mean it just keeps on rainbowing it will never go to yellow or white when i say "Ok, homey" and checking with the api command it DOES have results. Its just not listening to me anymore , like the microphone is suddenly off or something.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.19
