### ISSUE TITLE
Homey died after update 0.8.22

### ISSUE THREAD

**Issue by CootNL** [athombv/homey#325]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**
homey running
*Please include detailed steps how we can reproduce the issue*
restarting homey

**What was the result?**
After restarting homey I can reconnect to the wifi of homey but when connecting to my own wifi.
Homey died. The ring is out and also i cannot connect to homey.
...

**What did you expect as result?**
Homey to start
...

**Any other remarks**
homey is not working any more.
Edit Restarted several times but after restart and trying to contact homey, homey died every time.
...

**Comment by evad1st** [comment]
Simular here, however getting a wifi connection time out on my pc, and jumps back for a retry, and a few minutes later homey confirms a connection... So reset again, and again and again .....

**Comment by RemonBerends** [comment]
+1

**Comment by evad1st** [comment]
Okay, latest update: Finally after hours and hours of resetting and trying finally I could get it alive again ..... However, still have major issue's (IR still not working ..... (Yesterday I had a one time event Homey sent a signal which was received by the objective with the requested result .... So I start again ......<sigh>  Just try to add an app, no success --- still getting error <no success> try again ....
Just about ready to sell the damn thing.....I accept a lot of work to be done,but after about 2 years of developing, it's becoming ridiculous ..... basics should work ..... not even getting a response on time or date most of the time ...... sad, because I really believe in the concept and the future possibilities of this...

**Comment by RemonBerends** [comment]
@CootNL did you get your Homey also up and running again? I have still the same prob 😕

**Comment by CootNL** [comment]
Yesterday I have homey up and running again.

**Comment by RemonBerends** [comment]
Mine is also recovered.

**Comment by jeroenvollenbrock** [comment]
Please contact support@athom.com if this issue persists.
