### ISSUE TITLE
433 Mhz communication unavailable after reboot

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#340]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

I just had to do a reboot due to issues with Zwave (no response anymore, restart zwave chip didn't help). 

After that, Zwave was back, but now all 433 Mhz communication is lost ( i have a mix of Kaku and Action sockets).  Both receiving (via remote) or transmitting isn't working.

The first reboot didn't succeed in getting the Homey back online (it seemed to stop in the shutdown procedure). I had to do a power unplug to get it booted again.

Multiple reboots (either via software or power) don't help, 433 will keep being unavailable. 
I've done reboots earlier with 0.8.22 , there was never an issue with 433. 

Log: 9C5B721997

**What was the result?**

433 Unavailable

**Any other remarks**

I didn't test a 433 communication just before the reboot, so it might not be related to the fact that I was fiddling with Z-Wave.

**Comment by ReinierH** [comment]
Unfortunately the connection with the microcontroller times out when the booting process takes longer than usual. It looks like the problem arises on boot when having a lot of apps/devices installed. I've experienced the problem myself and fixed it by increasing the timeout value. This bug will be fixed in the next update.

**Comment by ralfvd** [comment]
Can you be specific which update this will be? Is it 0.8.24 ?

**Comment by ralfvd** [comment]
Confirmed to be working again in 0.8.24
