### ISSUE TITLE
[minor] "unresponding  z-wave node" is working as expected

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#359]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

On the Z-wave status page, one battery powered node is shown as 'non-responsive'. However, it is working as expected.

I used the device, refresh the page but then it is still working.

**What was the result?**

![screen shot 2016-03-18 at 11 09 22](https://cloud.githubusercontent.com/assets/17275712/13874766/26d23986-ecfa-11e5-90bd-929286cfa877.png)

**What did you expect as result?**

No error shown. 

Logfile: 575B022C46

**Comment by ocatie** [comment]
This can happen for battery devices. Because most battery device are sleeping node they cant be reached at any time (99,9%) thus a send command fails and the node is listed as failed. This does not impact any process in Homey.

A node needs to be registered as failed for it to de removed using the Failed Node process. Thus when refreshing a node a frame is send, fails, and the remove/replace failed node buttons appear.

**Comment by jghaanstra** [comment]
This happes to me on powered Greenwave node devices as well.
