### ISSUE TITLE
Zwave Set Homey Primary Controller - devices added as controller

### ISSUE THREAD

**Issue by jcastrol07** [athombv/homey#368]
**What is your Homey version (Settings → System)?

Homey Firmware Version: 0.8.24

**What did you try to achieve?

I had an existing Zwave controllar (by z-wave.me) where I had associated 17 devices (14 power nd 3 battery operated; and 10 are Fibaro devices and the other ones are Greenwave 6 powernodes) and I wanted to manage all the devices through Homey
So I set Homey as my primary Zwave Controller by including it in my current controller with that purpose

*Please include detailed steps how we can reproduce the issue*
- Have a current zwave controllar with devices running
- Set Homey as primary Controller

**What was the result?**
- Homey was included as a device in my current controller but interview was not completed. Also Homey is not recognized yet within the list of certified devices "http://pepper1.net/zwavedb/."
- My devices transfered somewhat to Homey but they are not usable because none of the parameters actually transfered so I do not know which device is which and even if all of them powered

**What did you expect as result?**

I expected all devices would appear with all of its parameters and details in Homey o be able to manage them in flows. I also expected that Homey zwave would appear in my current controller and interview could be completed
See file with screenshots
**Any other remarks**

Can someone tell me how to proceed s that I can use my zwave devices in Homey from here?
[Uploading Homey.docx…]()

**Comment by jcastrol07** [comment]
[Homey.docx](https://github.com/athombv/homey/files/185141/Homey.docx)

**Comment by jcastrol07** [comment]
This is how homey device interview does not complete

![image](https://cloud.githubusercontent.com/assets/17325004/13970775/3ac2c0ca-f08b-11e5-8c44-076a88831fe1.png)

**Comment by ocatie** [comment]
When you include Homey in an existing network, Homey tries to interview all devices in the network and adds them if the interview doesn't fail. If a device supports the configuration commandclass not all configuration parameter values are fetched. This because Homey doesn't know which parameters are used in your device (this will come later with apps).

If a device isn't added automagically you can select the node id in the dropdown menu and press Refresh Node. If no errors occur during the following interview your device is added.

It seems you devices are added with the Z-Wave controller device class. This shouldn't happen, I'll look into that. At the moment it is not possible to change the device class of a device once it is added. You have to remove the device and add it using the pairing wizard in Homey.

Besides that, I don't see anything out of the ordinary in your screenshots.

**Comment by ocatie** [comment]
Could you try to reproduce the devices in your current network being added as controller on 0.8.32?
