### ISSUE TITLE
Logic card only triggers when "is not" tick is selected

### ISSUE THREAD

**Issue by moekdegroot** [athombv/homey#380]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**
use the logic card in a flow using an "is" value

*Please include detailed steps how we can reproduce the issue*
Use the logic card in the and-column and drag a token from the if-column without selecting the "is not" tick in the logic card.

**What was the result?**
the flow doesn't run

...

**What did you expect as result?**
the flow to run

...

**Any other remarks**
I tried a couple of triggers but the result stays the same.
![logic-card](https://cloud.githubusercontent.com/assets/16590284/14104324/f8a66010-f5a4-11e5-8736-72a188879d48.jpg)

...

**Comment by Dijker** [comment]
@moekdegroot 
I think you test something that does not work the way you expect:
1st, did you test for real (Setting a reminder, leaving home, sending an email) or did you just save and press te Test button?

You have to know that when you press Test the programmer of  the software decides what dummy values (from the trigger in column 1) are used. Sunrise and Sunset is is always at 21:23 (see my answer in #182) 
In Pressence: everyone in test in John Doe, 
and Joey the author of Email wrote in the app: (https://github.com/HiemstraJ/homey.email/blob/master/app.json lines 44 - 60 
the examples: Subject /  Onderwerp / Senders: joe@example.com / piet@voorbeeld.nl")
I read somewhere (forum or GitHub) they change in I guess the next firmware to ask the Values for the labels on pressing the Test button.

Because you guessed wrong, all ...AND... triggers where wrong and give a red cross, by denying (Checking "Is_Not") alle checks are correct and give a green checkmark on pushing the test button. 

2nd, a Logical Compare " 'SomeoneWhoLeft' is bigger than 'Moek de Groot' "  is technically possible in the programming language they use, (see the reference from Emile in another topic to https://xkcd.com/1537/ )  but you never know what the result is... 

for example: My testflow with the correct value for Subject triggers as expected (on pressing Test). 

![image](https://cloud.githubusercontent.com/assets/12412734/14187024/730229ec-f781-11e5-85b5-ccae9a769ea8.png)

I am almost sure it also works when I test it for Real. 
Like this test, it denied on the test button (redX)
![image](https://cloud.githubusercontent.com/assets/12412734/14187281/9208b65c-f782-11e5-82d7-bbb37d6a4759.png)

but it functioned on scanning the correct card: 
![image](https://cloud.githubusercontent.com/assets/12412734/14187352/d8b4fd2c-f782-11e5-8370-30f7e5e4ea76.png)

Regards, Happy testing.....

**Comment by moekdegroot** [comment]
Thanks for explaining!
I didn't know about those dummy values and that would explain why they only work when the tick is enabled when tested :smile: 
I have two flows that used to trigger on emails with the words sunset and sunrise which would turn the lights outside on or off (the bottom one in my included picture).
Homey was in a box for 2 weeks and when I unpacked it this week I upgraded to 0.8.24.
That night the email trigger didn't work.
That's why I started testing but was unaware of the dummy values.
I don't have an android phone, have disabled the mic and can't find my nfc tags anywhere so email is the only way for me to check if it works.
I just tested some more and created a flow that only requires an email and has no conditions so any email should trigger it and still nothing happens even though the email app shows it received the mail.
So it looks like it's not a logic card problem but an email problem.
I think I should close this issue.
Thanks again!

**Comment by moekdegroot** [comment]
FYI
Just thought of a way to fake my presence without a phone and the logic card works as it should.

**Comment by Dijker** [comment]
maybe as an alternative to an android phone/tablet:
store the label in a variable and view it in the Settings/dashboard. (https://apps.athom.com/app/net.i-dev.betterlogic)
or open on Homey's IP /manager/speech-output/ and let Homey Say something ;-) 
Lol: 
(Test on NFC Tag )
![image](https://cloud.githubusercontent.com/assets/12412734/14189450/9a35a4ec-f78d-11e5-9aca-9c3e66cb2dba.png)
O-one column twenty-three column forty-five column  sixty-seven

or test scanning your Passport /ID Card (Generates a random ID ;-) ) of OVChip Card.
