### ISSUE TITLE
IR reception only works when the LED ring is off

### ISSUE THREAD

**Issue by MdeRhoter** [athombv/homey#394]
**What is your Homey version (Settings → System)?**

0.8.27

**What did you try to achieve?**

Use IR signals to trigger flows

**What was the result?**

The IR signals from the successfully recognized remote only trigger something when the LED ring is completely off

**What did you expect as result?**

I'd expect IR to work with the LED on, not necessarily at 100% brightness, but definitely at 1%.

...

**Comment by goldenice** [comment]
The LED-ring causes interference on the IR receiver. It generally does work though, although the distance at which the receiving starts may be less than with the LED-ring on. Did you pair the signal manually, or did you use an automatically detected signal in the pairing wizard? If you manually copied the signal to Homey, it might have used the wrong carrier frequency for your remote. It's pretty technical to explain, but using the wrong carrier may work, although the distance at which the remote is recognized will be very short.

I'll see if I can improve this in an future update, to be continued...

**Comment by freemann** [comment]
"_The LED-ring causes interference on the IR receiver._"
Ouch....

Will that be fixed/"patched" in later hardware releases/versions of Homey?

**Comment by goldenice** [comment]
Maybe, we're not sure yet. It's not that big of a deal actually, it is enough interference to be noticable, and to influence the maximum receiving distance, but that's about all, we can work around it properly. It certainly doesn't contribute to the range, but it isn't that hurtful to the range either. However, combined with the wrong carrier frequency of the IR signal, it just might be enough to decrease the range to something unacceptable.

**Comment by freemann** [comment]
:low_brightness:

**Comment by MdeRhoter** [comment]
What's a good IR remote for Homey? For instance, which one did Athom test with? I'd like to use the same one (easily done with a Harmony since that can emulate almost any remote) and see if I can keep the LED ring on.

**Comment by MdeRhoter** [comment]
Hello?

**Comment by goldenice** [comment]
Sorry to reply so late, I totally missed your comment in the storm of issues. My bad.

I have tested with a generic Philips remote, and some LG remotes as well. Philips is probably best, because they have a way better protocol than anything else. I don't want to get too technical, but Philips has RC6, which is well-defined and quite easy to detect and send out. Any newer philips remote should work properly, although the key mapping may be a bit off.

That being said, we do plan to improve IR for other brands as well. It's just that because RC6 (and RC5, it's predecessor) are a bit more complicated we tested those more thoroughly than other remotes, which ironically means that RC5 and RC6 work exceptionally well, and the rest not that well.

**Comment by MdeRhoter** [comment]
No problem, thanks for the tip - I'll go try out a few Philips remotes! Enjoy the weekend :)

**Comment by MdeRhoter** [comment]
Wow - what a difference, I configured a Philips remote (added the 65PUS7600 to the Harmony Hub) and everything just works! That should be in a FAQ somewhere :)

**Comment by MdeRhoter** [comment]
Quick update on 0.8.32; IR reception (with the above RC6 IR device) still only works when the LED ring is off. Rainbow at 1% brightness causes it to no longer receive IR commands (the Harmony Hub is about 50cm away).

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
