### ISSUE TITLE
Kaku broken

### ISSUE THREAD

**Issue by edtst** [athombv/homey#461]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Use my working Kaku modules

*Please include detailed steps how we can reproduce the issue*

Install 0.8.30

**What was the result?**

Kaku broken

**What did you expect as result?**

Working Kaku. I tried reinstalling modules, the app will not reinstall (something went wrong, no details), rebooting. Nothing works.
...

**Any other remarks**

...

**Comment by ReinierH** [comment]
Can you provide more information about the problem? Is it only kaku or are there any other 433Mhz apps that wont work either?

Could you report the problem (Settings->System) and give me the report id?

**Comment by edtst** [comment]
I only have Kaku. Here is the ID: CCD8A14C46

**Comment by cjvs** [comment]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Pair KAKU devices (sensors AMST-606 & wall switch AWST-8802)

**What was the result?**

Sensor was only found after 10 or more attempts (even next to homey), wall switch is detected after several attempts, however not reacting consistent. Better working when next to homey, however at a otherwise reasonable range of 8 meters with line of sight, the wall switch presses are not detected.

**What did you expect as result?**

Possibility to pair without multiple attempts, and working at a range of 8 meters with clear line of sight.

**Any other remarks**

none

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by cjvs** [comment]
With homey version 0.8.39 and kaku app 2.0.5 the sensors data is still not correctly or intermittently read / found Sensor is in a clear line of sight and 5 meters away. My homewizard which is further away ánd behind a wall does get all the readings...

**Comment by jeroenvollenbrock** [comment]
Have you tried to re-pair the devices and rebooting homey by pulling the plug? If that (temporarily) fixes the issues, Homey version 0.9.0 should resolve this
