### ISSUE TITLE
Aeotec MultiSensor 6 does not recognize all sensors

### ISSUE THREAD

**Issue by Rubelke** [athombv/homey#497]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.30
Aeotec/AEON Labs MultiSensor 6 

**What did you try to achieve?**
Get motion and vibration sensor responding.
the two sensors seems not to respond/trigger in homey.
I did a clean install from the sensor and only 5 out of 6 sensors are recognized by homey according the Insights.

**What was the result?**
![image](https://cloud.githubusercontent.com/assets/18566973/14760285/36385a06-0940-11e6-95f0-0be01b8bd11d.png)
![image](https://cloud.githubusercontent.com/assets/18566973/14760291/564d3fd2-0940-11e6-9611-cd12e7fa0526.png)

Missing data entry points from these two sensor values. Only Generic alarm is available but does not doing anything.

**What did you expect as result?**

All 6 sensor values visible in insights and by the information screen in devices.

**Any other remarks**

The vibration sensor seems to work on the sensor it self because the blue information led blinks during movement. 

 crash log data: 632F3ADBFE
...

**Comment by RobinBol** [comment]
It appears you are using the pre-rewrite z-wave module. From 0.9.2 z-wave is improved a lot, I am working an Aeotec specific app (MultiSensor already working on Github), which will probably resolve many of your issues (except for the tamper (vibration) alarm, which is not supported as of yet do to lacking documentation).

Could you let us know if this issue is still a problem for you?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
