### ISSUE TITLE
Flow seems to trigger twice with IFTTT Maker channel

### ISSUE THREAD

**Issue by bierre** [athombv/homey#510]
**What is your Homey version (Settings → System)?**
0.8.30

**What did you try to achieve?**

- I created a flow that is triggered by any NFC tag.
- The flow triggers IFTTT maker channel which logs the action in Evernote.

**What was the result?**

The event is logged twice in Evernote

**What did you expect as result?**

The event is logged once.

**Any other remarks**

...

**Comment by RobinBol** [comment]
I tried to reproduce, but without success. I am quite certain the app does not contain the bug, as there is not much that can go wrong. It receives a flow trigger and makes the request to IFTTT only once.

If you could provide a more detailed reproduction scenario perhaps I could reproduce.

I think this is issue might be caused due to the NFC reading, perhaps it read it twice as you held the tag near Homey in a way that made it trigger twice.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!

**Comment by bierre** [comment]
Didn't occur anymore. Might have been Some interferentie from HomeWizard. Thanx
