### ISSUE TITLE
Voice homey stammers

### ISSUE THREAD

**Issue by Robinyoh** [athombv/homey#550]
**What is your Homey version (Settings → System)?**
0.8.32 Dutch

**What did you try to achieve?**
Let homey say something

*Please include detailed steps how we can reproduce the issue*
Make a flow to let homey speak

**What was the result?**
Homey speaks, but the voice stammers sometimes.
...

**What did you expect as result?**
stammer free voice
...

**Any other remarks**
looks like the audio is breaking down sometimes, you hear some pops and clicks. You will hear this best when you have a long text. Also is the speed of the voice to fast i think.
...

**Comment by dhanstede** [comment]
I have also this problem. You can hear it when you use, for example,  the NOS headlines app. 
Version also 0.8.32 and dutch voice.

**Comment by jjtbsomhorst** [comment]
It depends on when and what you let it say. I'm currently at 8.0.29 and also have this issue.

**Comment by HackAzz** [comment]
I also have this and a loooot of other issues! 
Homey still needs a lot of work...

**Comment by Keverjeroen** [comment]
Hi, I never had a problem with the voice, but since **0.8.36**, Homey is stuttering almost all the time. I've the voice set to Dutch, with the male voice.

Example of a sentence that is always stottering:
_"Let op! De Volkswagen bus is aan het rijden!"_.

Homey can't say 'bus' without stuttering in this example.

When I let Homey say _"bus bus bus bus bus"_, there is no problem at all. So it looks like it is an combination of words that is hard for Homey.

**Comment by bvdbos** [comment]
Did you alter the voice-speed?

**Comment by Keverjeroen** [comment]
Voice-speed is at 'normaal'.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists in 0.9.2 or not?

**Comment by dhanstede** [comment]
After installing firmware 0.9.2 the voice of my homey does not stammers anymore.
