### ISSUE TITLE
Its not possible to remove a toasted unresponsive Zwave device from Homey

### ISSUE THREAD

**Issue by freemann** [athombv/homey#563]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Remove a toasted unresponsive Zwave device from Homey

**Please include detailed steps how we can reproduce the issue**

Plug in a Zwave device, wait for it to do the PLOF and then try to remove it from Homey.

**What was the result?**

The Zwave device did ( as expected :wink: ) PLOF, but i'm unable te remove it from Homey.

**What did you expect as result?**

After the Zwave device did PLOF, i could remove it from homey.

**Any other remarks**

...

**Comment by freemann** [comment]
hmm found that if I do a refresh node on the toasted GreenW, it becomes marked as "(failed)" and if you select a "(failed)" device, 2 new buttons appear and remove device should be possible.

So its possible to remove devices, but I think its not a very great UX.
Maybe add a section "settings>Zwave>[remove device]" with a list of devices and the user just can select the device and click "remove".

**Comment by ocatie** [comment]
If your device is physically broken and can't enter learnmode you can remode it by selecting it in the dropdown and try to Refresh the device. Because the device is broken it won't answer the command and the chip will place it on the failed node list. Now you can remove the device from Homey using the Remove Failed Device button.

**Comment by freemann** [comment]
I think I wrote almost the same..... and a bit more (suggestion).

Thanks!
