### ISSUE TITLE
Remote login with Android mobile chrome refresh Swipe in desktop version not working 

### ISSUE THREAD

**Issue by freemann** [athombv/homey#575]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Refreshing desktop version interface on Android Chrome by swiping from URL field down 

**Please include detailed steps how we can reproduce the issue**

- On a android phone start the chrome browser
- Login on my.athom.com
- Go to chrome settings menu
- Check the "desktop version" box
- In Homey interface go to "devices"
- Swipe from url bar down 
- Normally a website refreshes, Homey interface doesn't responde

**What was the result?**

Nothing happens 

**What did you expect as result?**

Web page refreshing 

**Any other remarks**

Android 6.0.1
Chrome 50.0.2661.89

**Comment by Dijker** [comment]
I confirm that it doesn't work refreshing by using the swipe down on the page. 
Exactly the same version of chrome on Samsung Galaxy Tab.

I consider that as a feature of the page because it provides the option to move the device cards using swiping on the page. I guess you can't have both features at the same time.

If I can choose, I will keep it this way, the browser still has a refresh button to use if you want.

**Comment by freemann** [comment]
Device Swipe is not possible in "desktop view".

**Comment by Dijker** [comment]
Yes, I confirmed it is not possible to swipe down to refresh is desktop view. 
But I don't have problems moving the device cards around on my chrome mobile. It works flawlessly both in desktop view and in the default mobile view mode.

**Comment by freemann** [comment]
Non issue....
