### ISSUE TITLE
Volume reset to 50% after unplug power

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#580]
**What is your Homey version (Settings → System)?**
0.8.32

**What did you try to achieve?**
Set the volume permanently on 75%, even after I unplugged the power

**What was the result?**
After I unplugged the power, the speaker volume is reset tot 50%.

**What did you expect as result?**
If I set the volume of the speaker to 75% and I do a reboot it's saved to 75%, if the Homey hangs, and I've to unplug the power cord, I expeced the volume stay's at 75%, and is not reseted to te default level

**Any other remarks**
At 0.8.29 the volume level was OK

**Comment by Dijker** [comment]
I read this and thought remarkable!! 
I have set the volume very low (approx 20)  in a firmware before there was a slider using the API... have restarted and powercycled my Homey many times. Upgraded almost direct with each new (experimental) firmware release. Never had to set the volume again..... Running 0.8.32 since day 1. 

Had to powercycle this morning and it was still 20%, Just tested again with 90% and aarestart and 75% and a restart and powercyle. Works as expected here. 
In my Homey I see no problems regarding the Volume setting after a un-plug. 
Maybe there is something different with your Homey, but for me your issue is remarkable...

**Comment by kerkenit** [comment]
On a reboot it's saved. 
I guess it has to do with the crash which happens couple times a day.

**Comment by WeeJeWel** [comment]
That's really odd. Does it also happen when you make some other settings, e.g. rename a flow?

**Comment by kerkenit** [comment]
No randomly. This happened if the Homey is more or less than 24 hours on. See the other reported bug. Sometimes within 4 hours it will hang

**Comment by kerkenit** [comment]
It's pretty stable today. I hadn't a crash today, but I als didn't rename a flow. If my Homey tomorrow still working, I'll rename a flow and wait until it crashes.

**Comment by kerkenit** [comment]
Until yesterday it's running stable. I've added some flows, renamed some.
Today it's crashed. After unplug the power the volume is reset back to 0.
That was the last volume level I've set.
