### ISSUE TITLE
KAKU broken in 0.8.34

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#602]
**What is your Homey version (Settings → System)?**

0.8.34

**What did you try to achieve?**
Adding KAKU socket and KAKU remote after a full reset and data erase of Homey

*Please include detailed steps how we can reproduce the issue*
Add device and then choose socket and then click on copy a remote or try to add a remote

**What was the result?**
Nothing happens
...

**What did you expect as result?**
adding a socket or remote

...

**Any other remarks**

...

**Comment by gkroone** [comment]
I have the same problem, but need to mention I had this problem already after a full reset and data erase on 0.8.32 so it might be something going back further.

**Comment by Fiek1** [comment]
Tried adding the sockets and remotes with another laptop of mine and this worked. Apparently there is something fishy in the browser of laptop I normally use

**Comment by CootNL** [comment]
KAKU is working perfectly with me

**Comment by gkroone** [comment]
Surprisingly, It actually does work when using my Galaxy S6Edge mobile Phone browser, but not on my Windows10 Chrome browser, nor from chrome installed on Linux mint 17.3 in virtualbox on that same PC. It also makes no difference to switch from one WiFi adapter to another in order to try from another IP.

Not sure if it's related, but chrome reports the following error:

![image](https://cloud.githubusercontent.com/assets/4581848/15290684/6d87084e-1b7a-11e6-809e-150986b70041.png)

**Comment by Dijker** [comment]
This Issue is getting really weird...
- Complaining KAKU is broken in .34 
- Someone complaining also having that problem but it didn't work before....
- then it works form another browser / laptop ????
- Then it works from a phone but not from a laptop for someone else ??? 

Pls keep the Issues and topics clear. 
- if you are talking about KAKU not working you can test it fe with a KAKU remote, add it to Homey as Device. Create Flow if Button x pressed = Puls LEDRing. 
IF that works? KAKU is receiving....

If you want to test sending KAKU? Create a flow to test switching a socket. IF that works? KAKU is sending... If Sending and Receiving = OK? then it is probably nog KAKU issue....

If you have Browser issues? you have them probably also using other things (other devices, other cards).

Create a clear topic what you experience and what you tried / when it happend.
Especially mention things like if it worked before  (fe < .34 ) and now not anymore. Or other things that changed where after it stopped.

If I read this above,  
three ppl with different issues,  probably all browser issues. 
- The developers for the browser issues skip it after reading the header.....
- no one in the KAKU team can do anything because it isn't a KAKU issue...

I suggest you close this issue, and open a new one with a clear title and description what you tried an what doesn't work. That will help everyone and maybe you also the fastest ....

**Comment by Fiek1** [comment]
@Dijker... The issue is very clear.. I tried to add a KAKU device with the laptop I normally use and that didn't work so I posted the issue here 

The next day I was playing with another laptop and tried to add a KAKU device and this worked so I posted a new comment. 

I still cant add a KAKU device with the laptop I normally use, so that's the only thing that's weird here.

**Comment by Dijker** [comment]
So it is probably a browser issue?

**Comment by Fiek1** [comment]
I have reset my browser settings and it still doesn't work in my laptop I normally use but I have added all my KAKU devices so I will close this issue

**Comment by Dijker** [comment]
thanks, 
imho your title was way te generic for an issue that probably belongs somewhere els....

**Comment by Fiek1** [comment]
thnx
