### ISSUE TITLE
Flow editor does not allow reordering cards in 'then' column

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#61]
On a flow with multiple 'then' cards I can drag a card, but cannot drop it on another position in the 'then' column.

**Comment by WeeJeWel** [comment]
Correct, this will be added later (it's pretty hard)

**Comment by matjaz** [comment]
As far as I see actions are executed parallel. With sequential actions we could achieve a lot more. Maybe for later.
Here is a short explanation https://forum.athom.com/discussion/815/improved-actions

**Comment by jghaanstra** [comment]
@matjaz this is not the case, you can set delays on each card which will make the chain sequential in the order they are sorted in the column.

**Comment by matjaz** [comment]
That's not the same. Delay is a fixed time.
Since actions are async action does not know how long will previous one take.

For example first action is get mp3 url, second action is play mp3. play mp3 needs to wait get url before executing. Also token would be required in this case, but that's another story.

**Comment by DieterKoblenz** [comment]
Cool. Was just writing an issue myself but fortunately decided to see if someone else had reported it.

**Comment by markaswift** [comment]
+ 1

**Comment by WeeJeWel** [comment]
Fixed in v1.3.0
