### ISSUE TITLE
Missing scrall bar on flow selection

### ISSUE THREAD

**Issue by spawnreaper** [athombv/homey#618]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.32

**What did you try to achieve?**

I have made more then 19 flows. If the list reaches the bottom of the chrome browser window it does not scrawl down further making the bottom flows inaccessible.

**What was the result?**

Several flows are out of bounds and can not be selected.

**What did you expect as result?**

scrawling down the list to see all the flows you made.

**Any other remarks**

nope, very basic.

**Comment by Dijker** [comment]
I think this is the same as #245 #274 #200 and others?
https://github.com/athombv/homey/search?q=scrollbar&type=Issues&utf8=%E2%9C%93 

There is a workaround at the forum, 
https://forum.athom.com/discussion/1011/simple-stylish-script-to-fix-some-ui-issues 

and it is fixed in 0.8.34 ;-)
(native available without the Sylish script)

**Comment by spawnreaper** [comment]
I can't seem to update to 0.8.34. Download and install automatically is turned on and experimental updates too.

**Comment by spawnreaper** [comment]
got it updated. working now.
