### ISSUE TITLE
Adding multiple lifx bulbs gets confusing without any form of ID.

### ISSUE THREAD

**Issue by spawnreaper** [athombv/homey#619]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.32

**What did you try to achieve?**

When adding multiple lifx bulbs to homey I noticed that the unique identity number or the personal name you gave the bulb is not displayed. Just a bunch of no name bulbs.

**What was the result?**

Had to add them one at a time so I knew which bulb was which.  

**What did you expect as result?**

Some marker that would identify one bulb from another. Preferably the name I gave the bulb in the Lifx app.

**Any other remarks**

**Comment by bvdbos** [comment]
![2016-05-18 21_52_30-homey zones devices](https://cloud.githubusercontent.com/assets/1064079/15372851/db4d6bb0-1d42-11e6-8a55-04618d389b3a.png)
Works for me?

**Comment by Dijker** [comment]
This is step 4 in adding devices:
https://www.athom.com/en/support/KB000003/
Give your device a name (optional)

**Comment by bvdbos** [comment]
I deleted my Lifx-lights to replicate this issue. Then I went on adding them and it showed the screen above. So it seems like it Lifx takes the names from the android-app (or actually from the lamps). Great thing: you can rename your lights in the devices-screen and changing the name in Homey gets reflected in the Lifx-app on my phone...

**Comment by spawnreaper** [comment]
@Dijker I know you can eventually add a name but when you start out and have 8 bulbs it did not five me a name like in your bvdbos his picture. It showed up as blank even though I did name my bulbs.

@bvdbos You say you removed and re-added the bulbs. maybe it is cached, or did you experience the same naming the first time you used your homey and added the bulbs for the first time?

**Comment by RobinBol** [comment]
@spawnreaper Thanks for reporting this issue. Where the labels initially blank? Like completely empty? Quite strange, as I just take the input from the bulb when I ask for their label..

**Comment by spawnreaper** [comment]
I added 5 bulbs, all blank. After adding them I had to figure out what bulb it was by turning them on so I could change the name accordingly. I do have to add this was the case when I first got my homey. I haven't added any bulbs since, so I am not sure if it was fixed already. 

There is also a problem with changing the bulbs color and dim level. The ball turns up to 100 for a second and then dimming down but the color is way off. I'm not sure if I already made a ticket about that.

Vriendelijke groet,

Vincent Jansen

**Comment by RobinBol** [comment]
Perhaps you used one of the earliest versions of the Lifx app which did not include the "labeling" functionality. I haven't encountered a similar issue, so I assume it is fixed by now. If you would check if you have the latest version of the Lifx app and try to remove/re-add your bulbs I expect the names to display properly.

Concerning the weird behavior of the bulb when changing dim/color, I also advise you to check if you are running the latest version of the Lifx app, and after re-adding your bulbs this issue should be resolved (fixed that in the latest release).

If one of these issues still persist, please re-open this ticket or create a new issue.
