### ISSUE TITLE
Homey prefers basic built in voice triggers over custom voice command triggers.

### ISSUE THREAD

**Issue by spawnreaper** [athombv/homey#622]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.32

**What did you try to achieve?**

Voice commands “turn the bedroom lights off” resulting in the bedroom lights off flow to be triggered.

**What was the result?**

Homey hears the words "Lights" and "off" in one sentence and it turns of all the lights.

**What did you expect as result?**

I made a flow with all my bedroom lights, I was expecting that flow to be triggered in stead of the invisible basic homey built-in voice commands.

**Any other remarks**

I have been fighting with homey to except my voice commands flows over the basic voice commands it seems to prefer. This is turning out to be a big problem.

**Comment by TedTolboom** [comment]
Currently, it is not possible to change priorities of custom flows over build-in commands. 

On the forum, the common practice is to avoid the build-in words like e.g. lights (or names of the rooms) within the triggers of a custom made flow.

You can try to use a different trigger, like if talking to a real person: "OK Homey, I'm going to bed" or "OK Homey, I'm going to sleep" and than trigger the flow based on the words 'going' in combination with either 'bed' or 'sleep'

I have a similar flow, turning of the lights in the living room, while I go to bed.

**Comment by spawnreaper** [comment]
Mmmm avoiding words like "lights" "Bedroom" seem to be the bare minimum to indicate what you want right? Hope they can improve this in the future.
I'll try to make some flows in the way you suggested.
Nevertheless I still think this can be considered a bug.

**Comment by Tweake** [comment]
We have researched the impact of changing the priority of flows in the past and decided not to change it. Instead, I have added the option to control your devices both per zone and by name of the device. 

These improvements are included in version 1.2.0, which will be available on all Homeys very soon. This should eliminate the issue your are having because you will no longer need flows to control specific devices by voice command. I would advise you to delete these flows is you still have them.

For more info about default speech commands as of version 1.2.0, check out: https://www.athom.com/nl/support/KB000037/
