### ISSUE TITLE
Athom App Store shows wrong install count for pending app

### ISSUE THREAD

**Issue by hilvarenbeek** [athombv/homey#645]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

As a developer, go to apps.athom.com , My Apps, (one of) your own app (in my case Marantz) that has a pending update (a version higher than current app store version). Note that the install count is empty, as is expected. Click to an older version of the app, note that the install count of that version is shown. Click back to the newer version. Note that the install count of the previously shown version remains on screen.

**What was the result?**

The shown install count is wrong (not hidden or shown as zero).

**What did you expect as result?**

The install count to be hidden or shown as being zero (no official installs because it hasn't been officially released yet)

**Any other remarks**

...

**Comment by joachimroeleveld** [comment]
I understand your confusion. However, the install count is not a version install count. It's the total app install count. What was happening is that on an update, the install count was "freezed" for that version of the app, which is why you see it changing as you're viewing an old version. 

This functionality changed in the meantime, but it's still visible for older versions. I will change this such that the install count is always the same, between versions. Thanks!
