### ISSUE TITLE
No distance option for geofencing

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#67]
I assume that the mobile phone app is sending its position to Homey? Is there any way to set the distance to trigger leaving/coming home?

**Nobody at home** is an interesting choice also for Presense

**Comment by goldenice** [comment]
Actually, the mobile app sets a radius around your home, and Android itself wakes up the app if you've entered or exited that radius. Currently it's 100m, but due to inaccuracies in GPS when indoors, it may trigger to much. Currently the app only uses geofencing, but I'd like to add wifi network detection and iBeacon support as well, so when two out of three methods report you're home, it doesn't drop as fast. However, this is a lot of work to build, so don't expect this by tomorrow please :stuck_out_tongue: 

A quick fix could be adding a timeout before leaving? So if Homey sees you're gone, and you 'come back in' after just a minute or so, Homey could just ignore that. How does that sound? I could also slightly increase the radius in the app to 150 or 200 metres or something like that, see if that helps...

**Comment by freemann** [comment]
The timeout "fix" sounds great!

**Comment by JohanKuster** [comment]
Ok goldenice as a quick fix it sounds ok. bt the way If have a flow on for 1 day now. Went all the riding 250 km today and never saw a message. In fact when I let the dog out I have to walk a lot more than 100m...no message, 

But what I realy would like like is a posibility to set the distance in the app.
But what I realy realy would like is let the flow decide when to let the trigger go off. Just send the coordinates and let the flow be the judge what to do. I guess that is a problem because it is using your server. You could send it directly to homey using some router settings etc. I have it working using a combination of Owntracks on Mobile phone and Mosquito and Node-red on a Raspberry.

**Comment by freemann** [comment]
Is Geofencing already implemented in 2.1 and/or when will it become available?

**Comment by goldenice** [comment]
This has been reimplemented in Android app version 2.2, and home detection no longer relies on distance, so I'll close this issue.

**Comment by freemann** [comment]
Could you give us some more info on how it should work now and what we may expect?

**Comment by goldenice** [comment]
Currently, the app gets a notification from the Android system whenever the wifi state changes. Whenever that happens, it'll check if it can reach Homey using the local IP. If so, it sets the present state of the user to 'at home'.

Then when the wifi state changes it'll check if it still can reach Homey. If it can't, then it'll location services is accurate enough at that moment to see if a person is leaving the house (accuracy < 100m). If so, it'll check using GPS if you're physically leaving, and then set the present state to 'away'.

The reason for the GPS part is that wifi signal might drop.

**Comment by elwin23** [comment]
Does it keep checking every so many minutes after leaving?

I turned this on two weeks ago but not until today I got my first message while already 45 minutes away from home, probably when IFTTT turned off my wifi toggle when entering "work" area through their geo-fencing.
I just disabled "App power saving" for the Homey app on my phone, as I have seen that functionality giving issues to apps in the past. Will let you know if this helped.

FYI, I added a flow that sends me a push message when entering or leaving my home.
