### ISSUE TITLE
Pull-down menu for notifications shows inactive devices

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/homey#672]
**What is your Homey version (Settings → System)?**

0.8.36

**What did you try to achieve?**

Creating a flow which sends a push notification to my mobile device(s)

**What was the result?**

Sending a push notification works. However, I have 3 devices listed in the pull down menu of which 1 is my phone, 1 the phone of my girlfriend and 1 device, I think, used to be my phone but after the Homey firmware updates and the mobile app update nothing happens when you select that device.

**What did you expect as result?**

That the pull-down menu only shows active devices. Or some kind of setting were you can select/delete the mobile devices which can receive notifications.

**Any other remarks**

Screenshot with the pull-down menu showing the three devices of which the android device - Jesper Janssen is not usable.
![image](https://cloud.githubusercontent.com/assets/17165733/15798510/4a364e7a-2a3b-11e6-89d2-9fc3af1cb89b.png)

**Comment by JesperJanssen** [comment]
After performing multiple re-installs of the Homey app (and clearing cache and deleting data) I now have 9 Galaxy S6 devices in the pull down menu.

![multiple devices](https://cloud.githubusercontent.com/assets/17165733/16176792/7303b1b0-3618-11e6-8b92-2519c04b86e0.jpg)

**Comment by JesperJanssen** [comment]
Tried to do a recovery of my Homey and erase all the data in the hope dat the list off inactive devices was gone but all devices are still there. Furthermore, I changed the name of my telephone so that I know which device I need to select (because I had 10+ S6 Jesper devices). But when selecting the new device I'm not able to send push notifications to my device anymore :(

**Comment by jeroenvollenbrock** [comment]
@JesperJanssen: Can you confirm the Homey App version 2.2.7 fixes this issue?

**Comment by JesperJanssen** [comment]
Hello Jeroen

After re-installing the Homey app on my phone and performed a factory reset off my Homey (and erasing all the data) the list is indeed shorter now. However, since I renamed my phone several times during previous testing there are still some inactive devices in the list (1 for each name I used).

The only active device in the list should be Galaxy S6 Jesper

![image](https://cloud.githubusercontent.com/assets/17165733/17588818/99c9b80c-5fd1-11e6-85b0-ff79bc5d94e3.png)

**Comment by jeroenvollenbrock** [comment]
@JesperJanssen There is no official way to do that yet, but we might add a "Delete all devices except this one" button to the settings screen of the mobile app in the future. If this feature is very important to you, please submit a new issue, so i can make sure the demand for this gets taken into account as well.

(One unsupported unofficial workaround that seems to work is to rename your device to the device you want to remove, kill and restart the Homey app, rename the device back to its original name, kill and restart the Homey app.)

**Comment by JesperJanssen** [comment]
Hallo Jeroen

Ik heb de work around geprobeerd maar tot nu toe is het me niet gelukt. Ik
heb sowieso ook een nieuw issue gesubmit omdat de lijst heel lang kan
worden als mensen hun apparaten af en toe een andere naam geven. Het lijkt
me dus wel een probleem wat een keer opgelost moet worden.

Gr. Jesper

2016-08-16 17:11 GMT+02:00 Jeroen Vollenbrock <notifications@github.com>:

**Comment by goldenice** [comment]
@JesperJanssen Yes, we agree, that is why we've slightly changed the way a device adds itself to your account. Since the Android 2.2.7 and iOS 1.2.1 update, a device will try to update itself when it notices that either a user already has a device with the same name, or a user has a device with the same device id. For example:

You reinstall the Homey app. A new device ID is generated (we can't uniquely detect the device across app installations) so in old app versions, a new device would be added to your account. With the new fixes, the device will recognise itself by it's name, and in my case it would see I already have a phone 'Nexus 5X Rick' in my account, so it would update the ID and tokens of that device.

If you change the name of your phone, the app will notice that there already is a device in your account with the same device ID, so it'll just update the name to the new one.

Additionally, if a device detects multiple devices with either the same name, or the same ID as it currently has, it'll remove every reference to that device except for the one most recently added. This means that if you have old device references in your account under another device name, you could temporarily change the name of your phone, start the app, keep it open for some time so it'll delete all duplicate references with that name (could take a while, depending on the amount of devices in your account and the speed of your internet connection), and then change the name of the phone back. If you do this for all unique names occurring in the list, the list should be clean and no inactive devices should ever show up again.

We're still looking into the best way to do manual deletion of devices, but with the fixes mentioned above, no duplicate references should show up, so the only way you'll ever get an inactive device attached to your account is to actually throw your phone away and buy a new one, and most users don't do that often ;)

**Comment by JesperJanssen** [comment]
Issue is fixed as part of the solution of issue#793
