### ISSUE TITLE
Date card does not give the correct date and time

### ISSUE THREAD

**Issue by posthok** [athombv/homey#695]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**
Set a date card in a flow and let homey speak the date set in the trigger.

*Please include detailed steps how we can reproduce the issue*
![31dec2015](https://cloud.githubusercontent.com/assets/6661318/16242802/8e251b0e-37f4-11e6-89ec-4ac8d47ffc6e.jpeg)

**What was the result?**
![31dec2015 1](https://cloud.githubusercontent.com/assets/6661318/16242812/96bb89f6-37f4-11e6-82fe-58e3105e8a8c.jpeg)

![31dec2015 2](https://cloud.githubusercontent.com/assets/6661318/16242937/2f95420c-37f5-11e6-94f1-06e56e7e6109.jpeg)

...

**What did you expect as result?**
The date set in the card
...

**Any other remarks**

...

**Comment by Arjanvde** [comment]
Did you run the flow or hit the test option as the test option fills in a predefined token for the date and time (not the actual time).

**Comment by bvdbos** [comment]
Works for me in Dutch...

**Comment by posthok** [comment]
@Arjanvde: Ok that explains it. But is there no way to check the input?

**Comment by Arjanvde** [comment]
@posthok Since I've got Homey I always created a flow like in the picture before setting the actual date and time to see what was happening and if the triggers worked as expected.

![schermafbeelding 2016-06-21 om 21 34 09](https://cloud.githubusercontent.com/assets/17526110/16244202/452ee036-37fb-11e6-9845-412ceb628a40.png)

I'm still using Slack as a tracking centre for timed flows (sunrise/sunset) and action flows lik If sunset triggers the light in the hallway and the Lights in the living room are off, that it has to trigger the night light on the living room.

So to check the input i would advise test on a time/date close by with a push notification to test if the flow worked.

**Comment by posthok** [comment]
@Arjanvde Thanx for your help. I'll get the picture. Will try it your way.
