### ISSUE TITLE
Generate custom signal for Kaku can cause duplicate signals

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/homey#754]
**What is your Homey version (Settings → System)?**

0.8.39
Kaku 2.0.6

**What did you try to achieve?**

I was adding a thirth APA3-1500R kaku switch when I noticed that after I paired it with a custom signal another APA3-1500R also triggered. 

So I paired new APA3-1500R again and still the generated signal is the same as previously generated signal.  

_Please include detailed steps how we can reproduce the issue_

See above 

**What was the result?**

A APA3-1500R which is situated in a different zone (bathroom in this case) got triggered by a flow that does not contain that specific device. 

...

**What did you expect as result?**
If I select 'generate signal' I expect that this signal is specific for that device or when that is not possible receive a notice and an option to abort. Because currently I can't use another Apar-150 and I'm wondering if this behaviour will be the same when I add for instance another ACM-1000? 
...

**Any other remarks**

...

**Comment by jjtbsomhorst** [comment]
Updated the issue with the correct device name

**Comment by BasKiers** [comment]
The generated signal should be different every time the "put device in pairing mode" screen is shown. So when you click previous on the "test device" screen the app will generate a new unique signals. The chance of getting the same signal as a paired device is 1 in ~6.000.000, but this is still a feature I will add down the road. For the old kaku devices there was much more chance of an id collision so I did temporarily implement it for the old kaku devices. If your issue is different please respond below, otherwise I will close this issue when I've implemented the check if the generated device is unique.

**Comment by jghaanstra** [comment]
I have experienced this same issue before and just ran into it again.

My current scenario, I have been using a KAKU APA2-2300R socket for some months now. I just paired and extra KAKU ACD-1000 socket which now reacts to the on/off signal of the already paired APA2-2300R socket.

Has the unique device id check been implemented already?

Firmware: 0.10.0
KAKU app: 2.6.6

**Comment by bvdbos** [comment]
close me
