### ISSUE TITLE
Homey does not speak first words in sentence when using external speaker

### ISSUE THREAD

**Issue by dhanstede** [athombv/homey#762]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Homey letting speak through an external speaker

*Please include detailed steps how we can reproduce the issue*

When i connect homey with a audio jacket to an external speaker, i don hear the first 4 a 5 words in the sentence through the external speaker. When homey speaks: 'Ik ben homey, en ik vertel je een verhaaltje', via the external speaker i hear '...ikvertel je een verhaaltje'.

**What was the result?**
I don hear the complete sentence throught an external speaker. If i don't use an external speaker, everything is allright and i hear the complete sentence.

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
This is most likely a problem with the speaker, and not with Homey. Some speakers try to detect sound before playing it by waiting until the volume has been above a certain treshold for a certain time before actually starting to play the sound. You can test this out by letting Homey play music and letting Homey speak while playing the music. If that works, the problem cannot be fixed in Homey. Maybe your speakers have a setting to control this behaviour?

**Comment by dhanstede** [comment]
I have tested it, and you are right. Thans for you're answer. I'll close this issue.
