### ISSUE TITLE
Flow card for "new value goes below|above old value"

### ISSUE THREAD

**Issue by freemann** [athombv/homey#799]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
If new Device variable value goes above|below old device value, then do X.
## _Please include detailed steps how we can reproduce the issue_

**What was the result?**
Can't find a card like that.

**What did you expect as result?**
search for a card where I can select a variable (power-usage, energy produced/used, times tripped, etc), set a tipping point value. In this way I can act on things like;
If dishwasher power usage goes from 100W to 5W then send push-message; Dishwasher is ready.

**Any other remarks**

**Comment by bvdbos** [comment]
In the plugwise-smile app this is already possible. Don't know if this is a core-feature or an app-feature?

**Comment by freemann** [comment]
If its "only" in the Plugwise App, then its probably a App card and not a Homey Core card.

**Comment by robertraaijmakers** [comment]
The result you want is already possible by adding a variable via better logic. I have my dryer and washing machine sending me a push notification when they are ready. To prevent a flood of push notifications I set the threshold (dryer started variable) high so that when my washing machine / dryer 'randomly' awakes (I don't know why it does that, but it does that sometimes in stand-by modus) it doesn't send me push notifications.

See attached screenshots for the flows.

<img width="999" alt="dryer finished" src="https://cloud.githubusercontent.com/assets/1773099/19265045/cb662f92-8fa3-11e6-8df8-4046f15c67ce.PNG">
<img width="999" alt="dryer started" src="https://cloud.githubusercontent.com/assets/1773099/19265044/cb5ff442-8fa3-11e6-9378-00c90ee47eac.PNG">

**Comment by bvdbos** [comment]
This has possible since a while now with tags, can be closed...
