### ISSUE TITLE
add media-manager to web-UI

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#808]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Turn off audio 

_Please include detailed steps how we can reproduce the issue_
Have a radio-station start as an alarm with
https://apps.athom.com/app/nl.santor.vradio
and try to turn it off

**What was the result?**
I had to go to 
http://<ip>/manager/media manually but the UI didn't scale. Then I had to change the browser-window to look like a phone for the media-manager to work.

**What did you expect as result?**
1) have a link to the media-manager in the first menu (next to "settings", "flows" etc)
2) have the UI working in maximized / general browser window

**Comment by TheMSB** [comment]
@bvdbos The Media Manager is currently not officially released yet as it is in active development. The current release date is not specified yet other than **_as soon as it's ready_**

I feel this issue is related to #809 , Please see the `Pause` and `Resume Playing` cards. They should be able to pause and resume your media playback respectively.

**Comment by bvdbos** [comment]
It's related but also a stand-alone request. We have this on our phones and on resized browser-windows if you know the trick and URL.

**Comment by TheMSB** [comment]
I am not sure I understand the request then. If you want the Media Manager to be available you will unfortunately have to wait a little longer. I promise we are working as hard as we can to get it to you as soon as possible though

**Comment by bvdbos** [comment]
fixed in 1.2.0
