### ISSUE TITLE
Restart zwave button is lost

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#827]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Zwave is crashing so i want to restart the zwave chip like we could before.

**What was the result?**

Button is lost since 0.9.x

**What did you expect as result?**

Plz put back the button in 0.1.0

**Any other remarks**

...

**Comment by caseda** [comment]
restarting homey (from settings) now restarts the z-wave chip as well

**Comment by Rocodamelshe** [comment]
Ok but that is way more time consuming me guess.
Restart Zwave chip in 0.8.32 took like 1,5 sec, restarting Homey takes like 2 min here.

**Comment by caseda** [comment]
Well, it shouldn't be needed to restart the chip (as much) since the library rewrite anyway.
Even with all my playing with the fibaro app, i only needed to reset (not even restart) the z-wave controller  once because of a different bug (not z-wave chip related).

never needed to restart the chip.

i think most of the time it's not even the z-wave chip itself, or the chip alone, but a combination, so need a full reboot of homey anyway :smile:

**Comment by freemann** [comment]
Z-wave reset +1 also +1 for repair button

**Comment by jghaanstra** [comment]
I'd like to see this return as well. Although I agree with @caseda that it should not be needed once zwave becomes more stable it currently just isnt stable eneough.

I have paired a Fibaro Motion Sensor Zwave+ about a week ago and since then the zwave chip crashes (or becomes constantly busy) almost once every day. Having to reboot every time is really time consuming and makes other flows not operational as well. The restart zwave button would solve all this.

**Comment by roelvdberge** [comment]
I would also like to see the return of the button (and hell yeah for a more stable Z-wave). It always takes me 2 attempts to connect Z-wave devices to Homey, no matter how close they are. First time I get a time-out, second time it usually works. From then on I can control my dimmers with Homey and the sensor passes data and updates variables, etc. Flows work like a charm...

...for a couple of days. And then Homey suddenly cannot connect to my dimmers which are physically less than 10 meters from Homey without obstacles. I have reset Homey in all possible ways, but this issue keeps popping up. The pulse-switches in front of the (powered) Fibaro FDG-212 (Z-Wave+) dimmers work without any issues. I thought that the sensor (Fibaro FGMS-001 EU V3.2) still worked but it seems the motion alarm doesn't send data back to Homey (I do see it light up). Luminance still works. 

The restart Z-Wave button did solve the issue previously but right now when I reset Homey it doesn't solve anything. Any help is greatly appreciated. If you need anything from me, please let me know!

Cheers, Roel

**Comment by WeeJeWel** [comment]
We won't add it back, as it's too complex (think of apps currently running for example). I'd rather fix the issues so it's not needed.
