### ISSUE TITLE
Strange pronouncing Dutch words

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#829]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?

Was updating from 0.9.2 to 0.9.3

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

"Homeee is aan het updaten, schakel Homeee niet uit voordat het updaten klaar is"

**What did you expect as result?**

Homey pronounces "Homey" as "Homeee" in Dutch. Maybe u guys could let Homey say "Homie" instead so he pronounces it better?
My daughters name is Sheila but I type Shiela in Homey so it sounds better.

**Any other remarks**

...

**Comment by Rocodamelshe** [comment]
Not solved in 0.10.0. Maybe later

**Comment by Tweake** [comment]
Included a fix in 0.10.1 for the pronunciation of Homey. Thanks for pointing out the issue :) 

As for the pronunciation of names in general; unfortunately that is something which we do not have direct control over. If a pronunciation bothers you the best option is to rewrite the name in a way that is phonetically closer to what you would like to hear, as you already mentioned. In your specific case the trouble is that the -ei- in Sheila needs to be pronounced the English way by the Dutch speech engine. Unfortunately we can't make such adjustments because it would cause other words to be mispronounced.

**Comment by Rocodamelshe** [comment]
The Sheila part was just an example.
Thnx!

**Comment by bvdbos** [comment]
I think you need some kind of pre-processing parser. " Sheila " (as an example and including spaces) could be transformed by Homey to " Shiela " and I'm sure there's tons of other words... 

Perhaps at the same time as the rewrite for English texts by a Dutch Homey is created?

**Comment by Rocodamelshe** [comment]
And with "included a fix in 0.10.1" u meant when we update from 0.10.1 to 0.11.0 it will be solved?

**Comment by Tweake** [comment]
@bvdbos: We would not want to start building a big ol' list of words and their replacements, since that would require continued maintenance. Another option I considered is to build a rule-based parser, which would extend the main parser that is already being used to create the speech now. There is a good reason that these rules aren't already included in the main parser though. Making the distinction between, say, "Ik ben Sheila" and "dat is Heiloo" can be very challenging. 

@Rocodamelshe It means that as soon as you have version 0.10.1 or greater running on your Homey this fix will be included.

**Comment by Rocodamelshe** [comment]
Cheers!

**Comment by bvdbos** [comment]
I understand the rule-based parser is probably impossible. However, for the future I would definitely consider keeping a (search-replace) list of words to get specific pronunciation (but low priority and only if it doesn't hurt performance too much...)

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in 0.10.1. If the problem persists, please reopen this issue.
