### ISSUE TITLE
[Mobile cards] Add power consumption mobile ui components/flow cards to devices supporting those capabilities

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#859]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

_Please include detailed steps how we can reproduce the issue_

Connect a Fibaro Wall Plug, add it as a light bulb.

**What was the result?**

Both flow cards and mobile ui components related to measure-/ meter_power are not present, even though the device/driver supports it.

**What did you expect as result?**

Those ui elements and flow cards to be present as the device supports it.

**Any other remarks**

This issue is created from https://github.com/athombv/com.fibaro/issues/25, and placed here as it is a generic issue (not specific to the Fibaro app). This issue will most likely be solved in an upcoming large update, due to the work that has already been done on the capabilities.

**Comment by TedTolboom** [comment]
@RobinBol @WeeJeWel when does this issue get solved? 

A lot of people expect to have the measurement capabilities included when they add a device as lamp (also due to the lack of note to indicate that this is not working)...

See the following topics:
https://github.com/athombv/com.fibaro/issues/136
https://github.com/athombv/com.fibaro/issues/92

and many more forum comments, like: https://forum.athom.com/discussion/comment/49925/#Comment_49925

**Comment by WeeJeWel** [comment]
Fixed in 1.2.1
