### ISSUE TITLE
KAKU Motion Sensor not working correctly

### ISSUE THREAD

**Issue by ronneman** [athombv/homey#863]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

Use the motion sensor APIR-2150 and AWST-6000.

*Please include detailed steps how we can reproduce the issue*

Add the devices and walk away a few meters from Homey. 

**What was the result?**

The alarm will go on but never off. When you are very close to Homey this does seem to work

**What did you expect as result?**

Clearly Homey has contact with the device since the alarm goes on. So I would expect it to go off as well. 

**Any other remarks**

Both the motion sensors have this same issue. On the forum there are more people talking about it: 
https://forum.athom.com/discussion/1777/klik-aan-zenden-werkt-niet-meer#latest

There are no objects blocking the signal. The problem starts already after 2 - 3 meters of Homey with clear line of sight. 

I have other KAKU devices further away that function without any issue. It is limited to these motion sensors.

**Comment by Dijker** [comment]
So you have to find out if it is Homey's problem or a problem from the PIR,
Did you try to learn the signal with a normal socket  and look if the socket switches at motion on/off at the same distance?
If the socket reacts always / consequently on the PIR we have to troubleshoot homey. If the Socket has the same problem  we can skip blaming Homey. 
My Experience is the APIR-2150 has a very crappy signal without Antenna mod.

I also tested simple CR2032 powered transmitters functioning at a intended place I would buy the APIR for, after placing the APIR (2x AAA powered) at that  point nothing than problems because of the bad signal transmitted...

**Comment by ronneman** [comment]
Do you have some more information about this Antenna Mod?

**Comment by Dijker** [comment]
Google Feel Lucky ;-) site:athom.com apir antenna

https://forum.athom.com/discussion/322/433-mhz-range/p2

**Comment by ronneman** [comment]
Thanks, I will try this when I have some time.
