### ISSUE TITLE
Perform capability.get on devices after reboot 

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#961]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

Installed Nest app and Nest Protect. The mobile card shows all correct alarm values (all off). Then I reboot and afterwards open the mobile card again.

**What was the result?**

Now the mobile card shows only the default empty values '-'.

**What did you expect as result?**

I expected Homey to perform a capability.get on the Nest Protect to fetch the current alarm values.

**Any other remarks**

It appears the capability.get is only performed after pairing of the device, and not after a reboot for example.

**Comment by WeeJeWel** [comment]
It should do this every boot. Are you sure you're not returning `null` yourself?

**Comment by RobinBol** [comment]
It indeed appears that the get is called before the driver was ready initializing the devices.

**Comment by WeeJeWel** [comment]
The get should be called when the driver's init callback is fired. If a get
happens before, that's a bug.

On Oct 8, 2016 15:21, "Robin Bolscher" <notifications@github.com> wrote:

Closed #961 <https://github.com/athombv/homey/issues/961>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/athombv/homey/issues/961#event-817086860>, or mute the
thread
