### ISSUE TITLE
Deleting a button when learning an IR remote

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#964]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

While creating a new IR device by learning from a remote I tried to delete a button. when all buttons in the list disappeared.

Add BUTTON 1
Add BUTTON 2
Remove BUTTON 1 or 2
(Whole list disappears)
Add BUTTON 3
(Whole list re-appears, including deleted button)

**What was the result?**

As soon as you delete a button, the whole list disappears. Until you add a new button and the whole list re-appears, including the deleted button.

**What did you expect as result?**

Remove the deleted button from the list.

**Any other remarks**

...

**Comment by bvdbos** [comment]
still happens in 1.5rc6

**Comment by BasKiers** [comment]
Hi,

I've tested this on 1.5.4 which is currently in developer preview and could not reproduce your issue. Since I've changed the pair wizard I assume this bug is fixed. Could you verify the bug is fixed when your Homey is updated to 1.5.4 and reopen this issue or create a new one if the problem still persists?

Thank you for reporting this issue!

Regards,
Bas
