### ISSUE TITLE
Homey randomly responding to words

### ISSUE THREAD

**Issue by Sateprikkert** [athombv/homey#99]
I set the Homey LED-ring to off when it's not doing anything. However, it never went off. Since I placed the Homey underneath my TV, it started to listen to random words (LED turning orange --> intensity changing while listening --> white --> blue), without triggering it with "OK Homey".

Every once in a while it gave an inaudible response in English, but while set to Dutch speech it said something like "...server... click try again later".

**Comment by Fire69** [comment]
+1
Random activation here also, and sometimes 'Oops, couldn't reach the server, ...'
I must admit, this was after doing the voice training with 4 different people.
When I redid the training alone, it was better but still activated once in a while.

**Comment by lvanderree** [comment]
+1
My homey is also randomly listening, without the trigger "Ok Homey".

Even this morning when I was in my kitchen, 10 meters away of the Homey and the rest of the home was quiet. 

I added a "parrot" flow, in which the homey repeats what you say after "Ok Homey", both as a push message to my phone, as well as spoken, and it "hears"/makes up many things, in a quiet house. Especially a lot of "no"'s, while I set my homey to Dutch.

**Comment by Sateprikkert** [comment]
(I should clarify that in my case it randomly activated with voice training by 2 persons)

**Comment by pkonings** [comment]
Same experience here, after only one time (setup) voice training

**Comment by coldshivery** [comment]
Yes sometimes out out nowhere it responds and goes back to idle or oops server did not respond.

**Comment by MuadDib007** [comment]
I can only say that I experience the same issue.
Even unplugged my Homey when watching a movie because I was getting annoyed.

**Comment by kingdong78** [comment]
same over here

**Comment by vogon1** [comment]
+1 - here also.

**Comment by denelan** [comment]
I have only tested my voice (female) and set the language to English. The tv and us at home speak Dutch. Randomly she tells the date and time, sometimes seems to listen or says things like 'sorry to hear that'(which I find rather amusing btw :)).
Because it is a pretty loud voice, we have to stop talking till she is done or we can't understand each other any more. I know volume is being worked on, but that is the part that makes it really annoying.

**Comment by gvanlee** [comment]
+1, Homey seems very sensitive and keeps hearing false OK Homeys.

**Comment by RuudBurger** [comment]
+1

**Comment by pkonings** [comment]
:+1:here too. Over the past 3 days it not only keeps "hearing false OK Homeys" but gives random reactions out of nothing. This is experienced as annoying too the other 's in the house asking me what the thing is supposed to be doing. (Of course a mitigate that until now ;-))

**Comment by denelan** [comment]
The other day we were treated by a song from Guetta, out of the blue.
Sensitivity seems to have been toned down. By now she doesn't respond to deliberate 'OK's' any more :) Either 'time' or flows.

**Comment by JesperJanssen** [comment]
I'm also struggling to get homey to accepts my "Ok Homey" (it's almost impossible). However, when I clap my hand 2 times I get 5 checkmarks after 5 tries. After that I just let Homey repeat what you asked him.

So I clap my hand two times and ask him "what is the time" or "what will the weather be tomorrow" and he repeats not even one word I asked him but something completely different like "go to" or "what the".

I thought you were using the speech recognizing software from Google for the Homey. But when I'm saying "Ok Homey" in the google translate app it actually writes down "okay homie". And Ok Google actually responds to my questions.

For now I will switch the voice control off because it's driving me crazy that he never responds to my ok Homey but responds to sounds in my house or on the television randomly.

**Comment by denelan** [comment]
I've made a flow where Homey (I have a female version ;)) says [I can't comply to {any word}]. It seems she picks up 'no' and 'now' (from Dutch spoken television) randomly.

**Comment by RemonBerends** [comment]
+1

**Comment by WeeJeWel** [comment]
Should be fixed with the default trigger since 0.8.34.
